Repository innovationacademy-kr/Cabi, pull requests merged in 2022-12, with the labels that each got.

#579 :wrench: 메인에서 어드민으로 API 요청을 할 수 있도록 nginx.conf 수정 #578
  dev/configure.conf
Labels: test

#581 토큰 인증 방식 수정 #580
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/config/configuration.ts
  backend/src/main.ts
  backend/src/middleware/session-middleware.ts
  frontend_v3/src/components/atoms/buttons/LoginButton.tsx
  frontend_v3/src/network/axios/axios.instance.ts
  frontend_v3/src/pages/Main.tsx
Labels: bug

#596 [FEAT] frontend_v4 폴더 추가 및 환경 셋업 #593
  frontend_v4/.eslintrc.json
  frontend_v4/.gitignore
  frontend_v4/.prettierrc
  frontend_v4/index.html
  frontend_v4/package-lock.json
  frontend_v4/package.json
  frontend_v4/public/vite.svg
  frontend_v4/src/App.css
  frontend_v4/src/App.tsx
  frontend_v4/src/assets/react.svg
  frontend_v4/src/index.css
  frontend_v4/src/main.tsx
  frontend_v4/src/vite-env.d.ts
  frontend_v4/tsconfig.json
  frontend_v4/tsconfig.node.json
  frontend_v4/vite.config.ts
Labels: enhancement, 환경세팅, frontend, v4

#603 [FE] v4 폴더 라우터 세팅
  frontend_v4/src/App.tsx
  frontend_v4/src/pages/HomePage.tsx
Labels: 환경세팅, frontend

#605 [FE] FEAT: 사물함 구역 상단 페이지네이션 바 구현 #598
  frontend_v4/src/assets/images/LeftSectionButton.svg
  frontend_v4/src/containers/SectionPaginationContainer.tsx
Labels: enhancement, frontend, v4

#600 [FEAT] Create Button Component#599
  frontend_v4/src/containers/ButtonContainer.tsx
  frontend_v4/src/containers/ModalContainer.tsx
Labels: enhancement, frontend, v4

#606 [FE] FEAT: 로그인페이지 추가 #604
  frontend_v4/src/index.css
  frontend_v4/src/main.tsx
  frontend_v4/src/media.css
  frontend_v4/src/pages/LoginPage.tsx
Labels: enhancement, frontend, v4

#614 [COMMON] DOCS: readme 4차 멤버, 문구 추가, 보완
  README.md
Labels: documentation

#617 [FE] FEAT: index.css gray-color 변수 추가
  frontend_v4/src/index.css
Labels: 환경세팅, frontend, v4

#620 [FE] FEAT: Left Navi 추가 #611
  frontend_v4/src/assets/images/close-square.svg
  frontend_v4/src/assets/images/log.svg
  frontend_v4/src/assets/images/search.svg
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/containers/TopNavContainer.tsx
  frontend_v4/src/index.css
  frontend_v4/src/pages/HomePage.tsx
  frontend_v4/src/pages/LoginPage.tsx
  frontend_v4/src/pages/MainPage.tsx
Labels: enhancement, frontend, v4

#621 [FE] FEAT: 파비콘, 타이틀 변경 #619
  frontend_v4/index.html
  frontend_v4/public/cabi.svg
  frontend_v4/public/vite.svg
Labels: enhancement, frontend, v4

#623 [FE] FEAT :Modal container, Floor Map 생성 #601
  frontend_v4/src/assets/images/checkIcon.svg
  frontend_v4/src/assets/images/errorIcon.svg
  frontend_v4/src/assets/images/exitButton.svg
  frontend_v4/src/containers/ButtonContainer.tsx
  frontend_v4/src/containers/MapGridContainer.tsx
  frontend_v4/src/containers/MapInfoContainer.tsx
  frontend_v4/src/containers/ModalContainer.tsx
Labels: FE, v4

#633 dev to main
  backend/src/auth/auth.controller.ts
  backend/src/auth/jwt/guard/jwtsign.guard.ts
  backend/src/ban/ban.module.ts
  backend/src/ban/ban.service.ts
  backend/src/config/configuration.ts
  backend/src/lent/lent.component.ts
  backend/src/lent/lent.module.ts
  backend/src/main.ts
  backend/src/utils/date.calculator.component.ts
  backend/src/utils/expired.checker.component.ts
  backend/src/utils/utils.module.ts
  frontend_v3/src/components/atoms/buttons/MenuButton.tsx
  frontend_v3/src/network/axios/axios.instance.ts
  frontend_v3/src/pages/Login.tsx
  frontend_v3/src/pages/Main.tsx
Labels: FE, BE

#613 [FE] FEAT: 메인 우측 구역(사물함 상세 정보) 디자인 구현 #607
  frontend_v4/src/assets/images/circleCabinetType.svg
  frontend_v4/src/assets/images/privateCabinetType.svg
  frontend_v4/src/assets/images/shareCabinetType.svg
  frontend_v4/src/containers/CabinetInfoArea.tsx
  frontend_v4/src/index.css
Labels: FEAT, FE, v4

#626 [COMMON] BUG: 대여 기간이 얼마 남지 않은 공유 사물함 대여 방지 기능 추가 #622
  backend/src/enums/lent.exception.enum.ts
  backend/src/lent/lent.component.ts
  backend/src/lent/lent.service.ts
Labels: BUG, FE, BE, v3

#635 [FE] FEAT: 캐비넷 아이템 디자인 구현 #598
  frontend_v4/src/assets/images/clubIcon.svg
  frontend_v4/src/assets/images/groupIcon.svg
  frontend_v4/src/assets/images/soloIcon.svg
  frontend_v4/src/containers/CabinetListContainer.tsx
  frontend_v4/src/containers/CabinetListItemContainer.tsx
  frontend_v4/src/pages/MainPage.tsx
Labels: FE, v4

#646 [FE] ETC: 우측 구역 컴포넌트 배치, 전체적으로 css 조정 #644
  frontend_v4/src/containers/CabinetInfoArea.tsx
  frontend_v4/src/containers/SectionPaginationContainer.tsx
  frontend_v4/src/pages/MainPage.tsx
Labels: FE, v4, FIX

#654 [BE] ETC: LOCAL=true일 때만 ServeStaticModule이 동작하도록 수정 #612
  backend/src/app.module.ts
Labels: BE

#650 [FE] FEAT: main.tsx에 recoil 코드 추가 #645
  frontend_v4/package-lock.json
  frontend_v4/package.json
  frontend_v4/src/main.tsx
Labels: FEAT, SETTING, FE, v4, FIX

#656 [FE] BUG: 로컬에서도 쿠키가 삭제되도록 수정 #655
  frontend_v3/src/components/atoms/buttons/MenuButton.tsx
  frontend_v3/src/network/axios/axios.instance.ts
  frontend_v3/src/pages/Login.tsx
  package-lock.json
Labels: BUG, FE, v3

#651 [FE] FEAT: 캐비닛 아이템 마우스 오버 시 애니메이션 개선 #647
  frontend_v4/src/containers/CabinetListItemContainer.tsx
Labels: FEAT, FE, v4

#649 [FE] FEAT: 좌측 섹션 구역 네비게이션 추가 #611
  frontend_v4/src/components/CabinetColorTable.tsx
  frontend_v4/src/containers/LeftNavOptionContainer.tsx
  frontend_v4/src/pages/MainPage.tsx
Labels: FEAT, FE, v4

#660 [FE] FEAT: 내 사물함 버튼 추가 #658
  frontend_v4/src/assets/images/myCabinetIcon.svg
  frontend_v4/src/components/TopNavButton.tsx
  frontend_v4/src/containers/TopNavButtonsContainer.tsx
  frontend_v4/src/containers/TopNavContainer.tsx
  frontend_v4/src/recoil/atoms.ts
Labels: FEAT, FE, v4

#669 [FE] FEAT: loading 컴포넌트 추가 #668
  frontend_v4/src/components/LoadingModal.tsx
  frontend_v4/src/pages/HomePage.tsx
Labels: FEAT, FE, v4

#671 [BE] FEAT: CI 단계에서 e2e Test를 위한 환경 셋업
  .github/workflows/cicd.yaml
  backend/test/app.e2e-spec.ts
  backend/test/cabinet.e2e-spec.ts
  backend/test/jest-e2e.json
Labels: FEAT, SETTING, BE

#657 [COMMON] REFACTOR: api v3 태그 제거 및 admin api 병합 #638
  backend/src/admin/admin.module.ts
  backend/src/admin/cabinet/cabinet.controller.ts
  backend/src/admin/cabinet/cabinet.module.ts
  backend/src/admin/lent/lent.controller.ts
  backend/src/admin/lent/lent.module.ts
  backend/src/admin/log/log.controller.ts
  backend/src/admin/log/log.module.ts
  backend/src/admin/return/return.controller.ts
  backend/src/admin/return/return.module.ts
  backend/src/admin/search/search.controller.ts
  backend/src/admin/search/search.module.ts
  backend/src/app.module.ts
  backend/src/betatest/betatest.controller.ts
  backend/src/cabinet/cabinet.info.controller.ts
  backend/src/lent/lent.controller.ts
  backend/src/main.ts
  backend/src/user/my.info.controller.ts
  backend/src/user/my.lent.info.controller.ts
  frontend_v3/src/components/atoms/buttons/MenuButton.tsx
  frontend_v3/src/components/atoms/buttons/ReturnButton.tsx
  frontend_v3/src/components/atoms/modals/ReturnBox.tsx
  frontend_v3/src/network/axios/axios.custom.ts
Labels: REFACTOR, COMMON

#680 [FE] FIX: 중복된 이미지 수정 #652
  frontend_v4/src/assets/images/circleIcon.svg
  frontend_v4/src/assets/images/clubIcon.svg
  frontend_v4/src/assets/images/club_circle.svg
  frontend_v4/src/assets/images/group_circle.svg
  frontend_v4/src/assets/images/privateIcon.svg
  frontend_v4/src/assets/images/shareCabinetType.svg
  frontend_v4/src/assets/images/shareIcon.svg
  frontend_v4/src/assets/images/single_circle.svg
  frontend_v4/src/assets/images/soloIcon.svg
  frontend_v4/src/containers/CabinetInfoArea.tsx
  frontend_v4/src/containers/CabinetListItemContainer.tsx
  frontend_v4/src/containers/InfoContainer.tsx
  frontend_v4/src/pages/MainPage.tsx
Labels: FE, v4, FIX

#678 [FE] FEAT: 버튼들에 recoil state 연결 #675
  backend/src/auth/auth.controller.ts
  frontend_v4/src/components/CabinetColorTable.tsx
  frontend_v4/src/containers/CabinetInfoArea.tsx
  frontend_v4/src/containers/CabinetListItemContainer.tsx
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/containers/LeftNavOptionContainer.tsx
  frontend_v4/src/containers/MapGridContainer.tsx
  frontend_v4/src/containers/MapInfoContainer.tsx
  frontend_v4/src/containers/SectionPaginationContainer.tsx
  frontend_v4/src/containers/TopNavButtonsContainer.tsx
  frontend_v4/src/containers/TopNavContainer.tsx
  frontend_v4/src/index.css
  frontend_v4/src/pages/HomePage.tsx
  frontend_v4/src/pages/MainPage.tsx
  frontend_v4/src/recoil/atoms.ts
  frontend_v4/src/recoil/selectors.ts
  frontend_v4/src/types/dto/user.dto.ts
Labels: FEAT, FE

#679 [FE] REFACTOR: promise to async #677
  frontend_v4/src/containers/TopNavContainer.tsx
  frontend_v4/src/pages/HomePage.tsx
Labels: REFACTOR, FE

#687 [FE] FEAT: Recoil state 연결 및 일부 기능 분리
  frontend_v4/src/components/CabinetInfoArea.tsx
  frontend_v4/src/components/CabinetList.tsx
  frontend_v4/src/containers/CabinetInfoArea.tsx
  frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
  frontend_v4/src/containers/CabinetListItemContainer.tsx
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/containers/SectionPaginationContainer.tsx
  frontend_v4/src/pages/HomePage.tsx
  frontend_v4/src/pages/MainPage.tsx
  frontend_v4/src/recoil/atoms.ts
  frontend_v4/src/recoil/selectors.ts
Labels: FEAT, FE

#690 [FE] FIX: v4 axios.custom.ts 수정 #688
  frontend_v4/src/api/axios/axios.custom.ts
Labels: FE, v4, FIX

#696 [FE] FEAT: TopNav 관련 수정 사항
  frontend_v4/src/components/TopNav.tsx
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/containers/TopNavContainer.tsx
  frontend_v4/src/pages/HomePage.tsx
  frontend_v4/src/pages/MainPage.tsx
  frontend_v4/src/recoil/atoms.ts
  frontend_v4/src/recoil/selectors.ts
Labels: FEAT, REFACTOR, FE, v4
