Repository innovationacademy-kr/Cabi, pull requests merged in 2022-07, with the labels that each got.

#126 :building_construction: 이벤트 제거 & Ban 처리 로직 적용 & URL 변경 처리 #112
  backend/app.ts
  backend/config/jwtConfig.ts
  backend/controllers/middleware/authMiddleware.ts
  backend/controllers/middleware/emailerMiddleware.ts
  backend/controllers/middleware/jwtMiddleware.ts
  backend/controllers/middleware/passportMiddleware.ts
  backend/controllers/middleware/slackMiddleware.ts
  backend/controllers/routers/apiRouter.ts
  backend/controllers/routers/authRouter.ts
  backend/controllers/routers/eventRouter.ts
  backend/email/ban.txt
  backend/email/lastoverdue.txt
  backend/email/overdue.txt
  backend/email/soonoverdue.txt
  backend/models/banModel.ts
  backend/models/dbModel.ts
  backend/models/eventModel.ts
  backend/models/queryModel.ts
  backend/models/types.ts
  backend/package-lock.json
  backend/package.json
  frontend/src/component/CabinetBox.tsx
  frontend/src/component/Carousel.tsx
  frontend/src/pages/Lent.tsx
  frontend/src/pages/Return.tsx
  frontend/vite.config.ts
  package-lock.json
Labels: enhancement, SKIM

#131 🧪 test jwt
  backend/config/jwtConfig.ts
  backend/controllers/middleware/authMiddleware.ts
  backend/controllers/middleware/jwtMiddleware.ts
  backend/controllers/routers/apiRouter.ts
  backend/controllers/routers/authRouter.ts
  backend/controllers/routers/eventRouter.ts
  frontend/img/cabinet.jpg
  frontend/package-lock.json
  frontend/src/component/Menu.tsx
  frontend/src/modal/ExtensionModal.tsx
  frontend/src/modal/LentModal.tsx
  frontend/src/modal/ReturnModal.tsx
  frontend/src/pages/Lent.tsx
  frontend/src/pages/Return.tsx
Labels: enhancement

#132 🚚 change console.log to console.error
  backend/controllers/middleware/passportMiddleware.ts
  backend/models/dbModel.ts
  backend/models/eventModel.ts
  backend/models/queryModel.ts
  backend/models/slackModel.ts
Labels: bug

#133 🔨 add new conditions in authCheck
  backend/controllers/middleware/authMiddleware.ts
  backend/controllers/middleware/jwtMiddleware.ts
  backend/controllers/middleware/passportMiddleware.ts
  backend/controllers/routers/authRouter.ts
  backend/controllers/routers/eventRouter.ts
Labels: enhancement

#134 🏗️ add conditions for jwt and session
  backend/controllers/middleware/authMiddleware.ts
  backend/models/types.ts
Labels: bug, enhancement

#135 🐛 update authMiddleware
  backend/controllers/middleware/authMiddleware.ts
Labels: bug

#136 🐛 update jwt value error
  backend/controllers/middleware/passportMiddleware.ts
  backend/controllers/routers/apiRouter.ts
Labels: bug

#137 ✨ add jwt token and remove event code
  backend/config/jwtConfig.ts
  backend/controllers/middleware/authMiddleware.ts
  backend/controllers/middleware/jwtMiddleware.ts
  backend/controllers/middleware/passportMiddleware.ts
  backend/controllers/routers/apiRouter.ts
  backend/controllers/routers/authRouter.ts
  backend/controllers/routers/eventRouter.ts
  backend/models/banModel.ts
  backend/models/dbModel.ts
  backend/models/eventModel.ts
  backend/models/queryModel.ts
  backend/models/slackModel.ts
  backend/models/types.ts
  frontend/img/cabinet.jpg
  frontend/package-lock.json
  frontend/src/component/Menu.tsx
  frontend/src/modal/ExtensionModal.tsx
  frontend/src/modal/LentModal.tsx
  frontend/src/modal/ReturnModal.tsx
  frontend/src/pages/Lent.tsx
  frontend/src/pages/Return.tsx
Labels: enhancement

#138 🐛 update passport middleware
  backend/controllers/middleware/passportMiddleware.ts
Labels: bug

#141 GA 주소 수정
  frontend/index.html
Labels: enhancement
