Repository innovationacademy-kr/Cabi, pull requests merged in 2022-06, with the labels that each got.

#102 🏷️ fix types to interfaces
  frontend/src/event/EventType.tsx
  frontend/src/types/cabinetTypes.tsx
  frontend/src/types/userTypes.tsx
Labels: documentation

#103 🐛 hide subscribe
  frontend/src/main.tsx
Labels: bug

#104 ✨ add redux and fix types to interfaces
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/Carousel.tsx
  frontend/src/component/Question.tsx
  frontend/src/component/map/SeromFloor.tsx
  frontend/src/component/map/SeromSecondFloor.tsx
  frontend/src/component/question.css
  frontend/src/event/EventType.tsx
  frontend/src/main.tsx
  frontend/src/modal/EventModal.tsx
  frontend/src/modal/QuestionModal.tsx
  frontend/src/modal/ReturnModal.tsx
  frontend/src/modal/questionModal.css
  frontend/src/pages/Lent.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/Return.tsx
  frontend/src/status/cabinetReducer.tsx
  frontend/src/status/index.tsx
  frontend/src/status/lentReducer.tsx
  frontend/src/status/userReducer.tsx
  frontend/src/types/cabinetTypes.tsx
  frontend/src/types/userTypes.tsx
Labels: documentation

#107 👍 성공적 첫 서버점검
  backend/models/queryModel.ts
Labels: 환경세팅, SKIM

#109 ✨ update Event Modal in Return page
  backend/controllers/routers/eventRouter.ts
  backend/models/eventModel.ts
  frontend/src/modal/ReturnEventModal.tsx
  frontend/src/modal/returnEventModal.css
  frontend/src/pages/Lent.tsx
  frontend/src/pages/Return.tsx
  package-lock.json
Labels: enhancement

#114 Feat/#113
  backend/controllers/middleware/passportMiddleware.ts
  backend/controllers/middleware/slackMiddleware.ts
  backend/controllers/routers/apiRouter.ts
  backend/controllers/routers/authRouter.ts
  backend/controllers/routers/eventRouter.ts
  backend/models/dbModel.ts
  backend/models/eventModel.ts
  backend/models/queryModel.ts
  backend/models/types.ts
  frontend/package-lock.json
  frontend/src/pages/Main.tsx
Labels: enhancement

#116 🐛 update getOverUser
  backend/controllers/middleware/emailerMiddleware.ts
  backend/models/banModel.ts
  backend/models/types.ts
Labels: bug

#118 ✅ update emailing system
  backend/controllers/middleware/authMiddleware.ts
  backend/controllers/middleware/emailerMiddleware.ts
  backend/models/banModel.ts
Labels: enhancement

#119 ✅ update emailing system
  backend/controllers/middleware/emailerMiddleware.ts
  backend/controllers/middleware/slackMiddleware.ts
  backend/models/types.ts
Labels: enhancement

#121 🧪 test for email log
  backend/controllers/middleware/emailerMiddleware.ts
Labels: test

#122 🧪 test for email log
  backend/models/types.ts
Labels: test

#123 🧪 test for email log
  backend/models/types.ts
Labels: test

#124 Feat #117 jwt 적용
  backend/config/jwtConfig.ts
  backend/controllers/middleware/authMiddleware.ts
  backend/controllers/middleware/jwtMiddleware.ts
  backend/controllers/middleware/passportMiddleware.ts
  backend/controllers/routers/apiRouter.ts
  backend/controllers/routers/authRouter.ts
  backend/controllers/routers/eventRouter.ts
  backend/models/banModel.ts
  backend/models/types.ts
  backend/package-lock.json
  backend/package.json
Labels: enhancement, SKIM
