Repository innovationacademy-kr/Cabi, pull requests merged in 2023-05, with the labels that each got.

#1074 [FE] BUG: 대여 시작 안 한 공유 사물함 기한 9999로 나오는 버그 수정 #1073
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
Labels: BUG, FE, v4

#1075 [FE] BUG: 공유 사물함 만료 일자 9999년으로 나오던 현상 수정 #1073
  README.md
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
Labels: FE, BE, v2

#1067 [BE] FEAT: spring test DB 및 기존 docker 셋업 추가
  backend/Dockerfile
  backend/database/init.sh
  backend/database/spring_test_db.sql
  backend/database/spring_test_db_v2.sql
  backend/docker-compose.yaml
  backend/docker-compose.yml
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetServiceTest.java
  backend/src/test/java/org/ftclub/jdbc/JdbcTest.java
  backend/src/test/resources/Dockerfile
  backend/src/test/resources/database/init.sh
  backend/src/test/resources/database/spring_test_db.sql
  backend/src/test/resources/database/spring_test_db_v2.sql
  backend/src/test/resources/docker-compose.yaml
  dev/configure.conf
Labels: FEAT, BE

#1079 [BE] FEAT: 서비스 계층용 인터페이스 추가
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/LentController.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentHistoryService
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentHistoryService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/main/resources/.gitkeep
Labels: FEAT, BE, SPRING_PORT

#1086 [COMMON] 어드민에서 검색 시 벤된 유저 UI 수정
  backend/src/admin/search/repository/search.repository.ts
  frontend/src/components/Search/SearchItemByIntraId.tsx
Labels: BUG, FIX, COMMON

#1091 [BE] FIX, TEST: 기존 검증 로직 보완 및 테스트 추가
  backend/src/main/java/org/ftclub/cabinet/auth/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/AuthAspect.java
  backend/src/main/java/org/ftclub/cabinet/auth/AuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/CookieManager.java
  backend/src/main/java/org/ftclub/cabinet/auth/OauthService.java
  backend/src/main/java/org/ftclub/cabinet/auth/TokenProvider.java
  backend/src/main/java/org/ftclub/cabinet/auth/TokenValidator.java
  backend/src/main/java/org/ftclub/cabinet/config/JwtProperties.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AuthControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiUriBuilderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/CookieManagerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/service/OauthServiceTest.java
Labels: BE, FIX, TEST, SPRING_PORT

#1096 [BE] SPRING Test에서 @AuthGuard를 사용하는 경우 토큰을 Mocking하는 TestUtils 구현
  backend/build.gradle
  backend/src/main/java/org/ftclub/cabinet/CabinetApplication.java
  backend/src/main/java/org/ftclub/cabinet/auth/AuthAspect.java
  backend/src/main/java/org/ftclub/cabinet/auth/TokenProvider.java
  backend/src/main/java/org/ftclub/cabinet/auth/TokenValidator.java
  backend/src/main/java/org/ftclub/cabinet/auth/User.java
  backend/src/main/java/org/ftclub/cabinet/auth/UserAspect.java
  backend/src/main/java/org/ftclub/cabinet/dto/UserSessionDto.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AuthControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/controller/CabinetControllerTest.java
  backend/src/test/java/org/ftclub/testutils/TestControllerUtils.java
Labels: BE, TEST, SPRING_PORT

#1104 [BE] BUG: 인트라 로그인 시 토큰 생성 오류 수정
  backend/src/main/java/org/ftclub/cabinet/auth/TokenProvider.java
Labels: BUG, BE, SPRING_PORT

#1108 [FE] FEAT: 타 사물함 대여 잔여일 표시#1106
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
Labels: FEAT, FE

#1112 [FE] FEAT: Admin 로그인 입력 폼 추가 #1109
  frontend/src/components/Login/AdminLoginTemplate.tsx
  frontend/src/pages/admin/AdminLoginPage.tsx
Labels: FEAT, FE

#1113 [BE] FEAT: 어드민 로그인 id, password 입력받는 방식 개선 #1109
  backend/src/admin/auth/auth.controller.ts
  backend/src/admin/auth/auth.service.ts
  backend/src/admin/dto/admin.login.dto.ts
  backend/src/config/configuration.ts
Labels: BE

#1111 [BE] Spring 포팅 - User
  backend/src/main/java/org/ftclub/cabinet/dto/UserCabinetDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UserCabinetPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/AdminRole.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicy.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanType.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/AdminUserRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/BanHistoryRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserExceptionHandlerService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/AdminUserControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/AdminUserRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/BanHistoryRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/UserRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserServiceTest.java
Labels: BE, SPRING_PORT

#1114 [COMMON] FEAT: 어드민 로그인 api 연결 #1109
  backend/src/admin/auth/auth.controller.ts
  backend/src/admin/auth/jwt/jwt.strategy.ts
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/Login/AdminLoginTemplate.tsx
  frontend/src/components/Login/LoginTemplate.tsx
Labels: FEAT, COMMON

#1116 [FE] FEAT/FIX: Admin 로그인 실패 시 모달 추가 및 사파리 admin 로그인 폼 수정 #1109
  backend/src/admin/auth/auth.controller.ts
  frontend/src/assets/data/maps.ts
  frontend/src/components/Login/AdminLoginTemplate.tsx
Labels: FEAT, FE, BE, FIX

#1118 [BE] SPRING 포팅 - User
  backend/src/main/java/org/ftclub/cabinet/auth/UserAspect.java
  backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UserProfilePaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicy.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicyImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/AdminUserRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/BanHistoryRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserExceptionHandlerService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/AdminUserControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/UserRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserServiceTest.java
  backend/src/test/java/org/ftclub/testutils/TestControllerUtils.java
Labels: BE, SPRING_PORT

#1120 [FE] FIX: 어드민 스타일 수정 #1119
  frontend/src/components/AdminInfo/Table/AdminTable.tsx
  frontend/src/components/AdminInfo/Table/Pagination.tsx
  frontend/src/pages/admin/AdminInfoPage.tsx
Labels: FE, FIX

#1125 [BE] Auth JSONObject -> JsonNode 사용으로 변경 및 리팩터링
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/ApiUriBuilder.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenProvider.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenValidator.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/OauthService.java
  backend/src/main/java/org/ftclub/cabinet/config/FtApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/GoogleApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/UserAspect.java
  backend/src/main/resources/application.yml
  backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiUriBuilderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/UserSessionControllerTest.java
Labels: REFACTOR, BE, FIX

#1131 [BE] WebClient 적용 및 리팩터링, 테스트 수정
  backend/build.gradle
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/ApiRequestManager.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/ApiUriBuilder.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/OauthService.java
  backend/src/main/java/org/ftclub/cabinet/config/ApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/FtApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/GoogleApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiRequestManagerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiUriBuilderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/service/OauthServiceTest.java
Labels: REFACTOR, BE, FIX, SPRING_PORT

#1129 [BE] SPRING 이벤트 임시 구현
  backend/src/main/java/org/ftclub/cabinet/event/EventTestService.java
  backend/src/main/java/org/ftclub/cabinet/event/LentEventListener.java
  backend/src/main/java/org/ftclub/cabinet/event/LentStartEvent.java
  backend/src/test/java/org/ftclub/cabinet/event/LentEventListenerTest.java
Labels: FEAT, BE, SPRING_PORT

#1136 [BE] BUG: admin에서 캐비닛 number로 검색 시 정렬 오류 #1135
  backend/src/admin/search/repository/search.repository.ts
Labels: BUG, BE, v4

#1139 [BE] FIX: ban 관련 변경
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyStatus.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentExceptionHandlerService.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicyImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanType.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
Labels: BE, FIX, SPRING_PORT

#1144 [BE] FIX: searchByCabinetNumber order 수정 #1135
  backend/src/admin/search/repository/search.repository.ts
Labels: BE, FIX

#1148 [BE] FEAT : 외국 유저 인증 불가 기능 추가 및 테스트 코드 작성 #1134
  backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenProvider.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
Labels: FEAT, BE

#1141 [FE] REFACTOR: Common 컴포넌트들의 서식과 import 경로 수정 #1137
  frontend/src/components/Common/Dropdown.tsx
  frontend/src/components/Common/Selector.tsx
  frontend/src/components/Common/WarningNotification.tsx
Labels: REFACTOR, FE, v4

#1142 [FE] REFATOR: 커스텀 hooks #1137
  frontend/src/components/AdminInfo/Table/AdminTable.tsx
  frontend/src/components/Modals/BanModal/BanModal.tsx
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
  frontend/src/hooks/useAdminHomeApi.ts
  frontend/src/hooks/useMultiSelect.ts
  frontend/src/hooks/useOutsideClick.ts
  frontend/src/pages/admin/AdminInfoPage.tsx
  frontend/src/recoil/atoms.ts
  frontend/src/types/dto/admin.dto.ts
  frontend/src/utils/dateUtils.ts
  frontend/src/utils/tableUtils.ts
Labels: REFACTOR, FE
