Repository innovationacademy-kr/Cabi, pull requests merged in 2023-09, with the labels that each got.

#1361 [FE] 사물함 페이지 새로고침 기능 추가 #1360
  deploy-dev/pinpoint-application/docker-compose.yml
  deploy-main/pinpoint-application/docker-compose.yml
  frontend/src/pages/MainPage.tsx
Labels: FE, v4, CHALLENGE

#1375 [BE] FIX: 메일 발신자 이름이 42CABI로 표시되도록 수정
  backend/src/main/java/org/ftclub/cabinet/config/GmailProperties.java
  backend/src/main/java/org/ftclub/cabinet/utils/mail/EmailSender.java
  backend/src/test/resources/application.yml
Labels: BE, FIX

#1372 [FE] FIX : IN_SESSION에서 상태 변경 시 올바른 상태 변경 가능#1371
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CountTime.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/pages/MainPage.tsx
Labels: FE, FIX, CHALLENGE

#1380 [FE] 새로운 Home화면 디자인 적용
  frontend/src/assets/css/homePage.css
  frontend/src/assets/data/ManualContent.ts
  frontend/src/assets/images/manualPeople.svg
  frontend/src/assets/images/map.svg
  frontend/src/assets/images/moveButton.svg
  frontend/src/assets/images/myCabinetIcon.svg
  frontend/src/assets/images/searchWhite.svg
  frontend/src/assets/images/select.svg
  frontend/src/components/Home/ManualContentBox.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
  frontend/src/components/Modals/ManualModal/ManualModal.tsx
  frontend/src/components/TopNav/SearchBar/SearchBar.tsx
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/types/enum/content.status.enum.ts
Labels: FEAT, FE, CHALLENGE

#1378 [BE] admin에서 연체된 사물함 반납 시 유저에게 ban 적용
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
Labels: FEAT, BE

#1387 Be/dev/feat admin api log/#1384
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/exception/ControllerException.java
  backend/src/main/java/org/ftclub/cabinet/exception/CustomServiceException.java
  backend/src/main/java/org/ftclub/cabinet/exception/DomainException.java
  backend/src/main/java/org/ftclub/cabinet/exception/ServiceException.java
  backend/src/main/java/org/ftclub/cabinet/exception/UtilException.java
  backend/src/main/java/org/ftclub/cabinet/log/AdminApiLogAspect.java
  backend/src/main/java/org/ftclub/cabinet/log/WebHookTestController.java
Labels: FEAT, BE
