Repository innovationacademy-kr/Cabi, pull requests merged in 2023-07, with the labels that each got.

#1233 [BE] FIX: AuthAspect의 쿠키 체크 로직 삭제 - 불필요함
  backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthAspect.java
Labels: BE, SPRING_PORT

#1237 [COMMON] FIX: backend-CI 변경
  .github/workflows/back-ci.yaml
  .github/workflows/back-cicd.yaml
  Dockerfile
  appspec.yml
  scripts/deploy.sh
Labels: SETTING, COMMON

#1236 [BE] FIX : 대소비교 수정 & 메소드 이름 수정 in lentRepository
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
Labels: BE, FIX

#1228 [FE] FIX: 대여기록 제목 클릭시 토글 검색 기능은 검색페이지에서만 가능하도록 수정
  frontend/src/components/LentLog/AdminLentLog.tsx
Labels: FE, FIX

#1232 [BE] FEAT: cabinet-simple 추가
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/dto/CabinetSimpleDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/CabinetSimplePaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
  backend/src/main/java/org/ftclub/cabinet/search/controller/SearchController.java
Labels: BE, v4

#1239 [FE] FIX: SearchBarList에서 사용하는 API를 cabinets-simple API로 변경 #1238
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/TopNav/SearchBar/SearchBar.tsx
  frontend/src/components/TopNav/SearchBar/SearchBarList/SearchBarList.tsx
  frontend/src/types/dto/cabinet.dto.ts
Labels: FEAT, REFACTOR, FE, FIX

#1247 [BE] User unit test 작성
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/BrokenCabinetPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/CabinetInfoPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/CabinetPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/LentHistoryPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/OverdueUserCabinetPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UserCabinetPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
  backend/src/main/java/org/ftclub/cabinet/mapper/LentMapper.java
  backend/src/main/java/org/ftclub/cabinet/mapper/UserMapper.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/AdminUser.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/user/domain/BanHistoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/domain/UserTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/AdminUserRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserServiceUnitTest.java
Labels: BE, v4, TEST, SPRING_PORT

#1250 [FE] BUG: LineChart 에러 해결 #1249
  frontend/src/pages/admin/AdminHomePage.tsx
Labels: BUG, FE

#1248 [BE] 시스템 스케줄러 관련 코드 & 테스트 코드 작성
  backend/build.gradle
  backend/src/main/java/org/ftclub/cabinet/auth/domain/ApiRequestManager.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/FtApiManager.java
  backend/src/main/java/org/ftclub/cabinet/config/FtApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/GmailProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/MailOverdueProperties.java
  backend/src/main/java/org/ftclub/cabinet/dto/ActiveLentHistoryDto.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/mapper/LentMapper.java
  backend/src/main/java/org/ftclub/cabinet/utils/DateUtil.java
  backend/src/main/java/org/ftclub/cabinet/utils/leave/absence/LeaveAbsenceManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/mail/EmailSender.java
  backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueType.java
  backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/templates/mail/overdue.html
  backend/src/main/resources/templates/mail/soonoverdue.html
  backend/src/test/java/org/ftclub/cabinet/utils/DateUtilTest.java
  backend/src/test/java/org/ftclub/cabinet/utils/leave/absence/LeaveAbsenceManagerUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/utils/mail/EmailSenderUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/utils/overdue/manager/OverdueManagerUnitTest.java
  backend/src/test/resources/application.yml
Labels: FEAT, BE, TEST, SPRING_PORT

#1252 [BE] TEST: 시스템 스케줄러 의존 모듈 테스트 케이스 추가
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/ApiRequestManagerUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/lent/domain/LentHistoryTest.java
  backend/src/test/java/org/ftclub/cabinet/lent/domain/LentHistoryUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/mapper/LentMapperTest.java
Labels: BE, TEST, SPRING_PORT

#1253 [BE] FEAT: 블랙홀 스케줄러 구현 및 테스트
  .idea/misc.xml
  backend/src/main/java/org/ftclub/cabinet/dto/UserBlackholeInfoDto.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
  backend/src/test/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManagerUnitTest.java
Labels: FEAT, BE, TEST, SPRING_PORT

#1259 [BE] ENHANCE: 스케줄러 관련 개선사항
  backend/src/main/java/org/ftclub/cabinet/auth/service/FtApiManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/leave/absence/LeaveAbsenceManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
  backend/src/test/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManagerUnitTest.java
  backend/src/test/resources/application.yml
Labels: BE, FIX, SPRING_PORT

#1244 [FE] : fix lentLog layout 화면 높이에 따른 깨짐 수정
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/LentLog/AdminCabinetLentLog.tsx
  frontend/src/components/LentLog/AdminLentLog.tsx
  frontend/src/components/LentLog/AdminUserLentLog.tsx
  frontend/src/components/LentLog/LogTable/AdminCabinetLogTable.tsx
  frontend/src/components/LentLog/LogTable/LogTable.tsx
  frontend/src/hooks/useMenu.ts
  frontend/src/pages/admin/AdminLayout.tsx
Labels: FE, v4, FIX

#1257 [BE] 층별 전체 사물함 조회 뷰 성능 개선
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Location.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/dto/ActiveCabinetInfoDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ActiveCabinetInfoEntities.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceUnitTest.java
Labels: FEAT, BE, FIX

#1268 [FE] FIX: 반납시간이 NULL 일 시 "-" 출력되게 수정 #1266
  frontend/src/components/LentLog/LogTable/LogTable.tsx
Labels: FE, v4, FIX

#1273 [FE] FEAT: 웹앱을 위한 PWA 적용 #1272
  frontend/index.html
  frontend/public/icons/icon-192x192.png
  frontend/public/icons/icon-256x256.png
  frontend/public/icons/icon-384x384.png
  frontend/public/icons/icon-512x512.png
  frontend/public/manifest.json
Labels: FEAT, FE
