Repository innovationacademy-kr/Cabi, pull requests merged in 2023-08, with the labels that each got.

#1295 [BE] LentPolicy 블랙홀 검증 로직 삭제
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
  backend/src/test/java/org/ftclub/cabinet/lent/domain/LentPolicyUnitTest.java
Labels: BUG, BE

#1299 [FE] FEAT : 초대코드 모달 구현 #1298
  frontend/src/assets/data/maps.ts
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
  frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
Labels: FEAT, FE, CHALLENGE

#1270 [BE] REFECTOR: 층 전체 조회 API 리팩토링
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
Labels: REFACTOR, BE

#1311 [FE] HOTFIX: 사물함 대여 존재 시 타 사물함 대여 불가
  backend/docker-compose.yaml
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/test/java/org/ftclub/cabinet/CabinetApplicationTests.java
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/Modals/UnavailableModal/UnavailableModal.tsx
  frontend/src/pages/Layout.tsx
Labels: FE, FIX

#1320 [FE] FIX: 대여 / 반납 시 버튼을 연속적으로 눌러 같은 요청을 반복적으로 보내지 못하도록 수정 #1315
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/components/Modals/Modal.tsx
  frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
Labels: FE, v4, FIX

#1308 [FE] FEAT :대여 대기 상태 사물함정보 화면 구현 #1306
  frontend/src/assets/images/clock.svg
  frontend/src/assets/images/subtract.svg
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CodeAndTime.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CountTime.container.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CountTime.tsx
Labels: FEAT, FE, CHALLENGE

#1332 [BE] FIX: 테스트를 인메모리로 돌리도록 수정
  .github/workflows/back-ci.yaml
  backend/src/test/java/org/ftclub/cabinet/CabinetApplicationTests.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/lent/repository/LentRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/AdminUserRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/BanHistoryRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/UserRepositoryTest.java
  backend/src/test/java/org/ftclub/jdbc/JdbcTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/data.sql
  backend/src/test/resources/database/spring_test_db.sql
  backend/src/test/resources/schema.sql
  scripts/deploy-dev.sh
  scripts/deploy-main.sh
Labels: BE, FIX

#1333 [FE] 대기열 취소 모달 추가#1327
  frontend/src/assets/data/maps.ts
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CountTime.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Modals/CancelModal/CancelModal.tsx
  frontend/src/recoil/atoms.ts
Labels: FEAT, FE, CHALLENGE

#1331 [FE] FIX: 3층 비밀번호 초기화 후 반납 시에도 같은 요청을 반복적으로 보내지 못하도록 수정 #1315
  frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.container.tsx
  frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
Labels: FE, v4, FIX

#1319 [FE] FIX: 지도 클릭 후 층 이동시 localStorage 의 CurrentSection 이 업데이트 되지 않아 해당 층에 없는 Section 을 보여주던 문제 수정 #1269
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
  frontend/src/components/MapInfo/MapItem/MapItem.tsx
Labels: BUG, FE, v4

#1329 [FE] FEAT: 공유 대여 빈납과 연장권 사용, 연장권 정보 확인시 띄울 모달 추가 #1317
  frontend/src/assets/data/maps.ts
  frontend/src/assets/images/extensionTicket.svg
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Modals/ExtendModal/ExtendModal.tsx
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/recoil/atoms.ts
  frontend/src/types/dto/user.dto.ts
  frontend/src/utils/dateUtils.ts
Labels: FE, v4, CHALLENGE

#1346 [COMMON] lent share api connection
  backend/build_be.sh
  backend/docker-compose.yaml
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/config/RedisRepositoryConfig.java
  backend/src/main/java/org/ftclub/cabinet/dto/CabinetInfoResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/MyCabinetResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ShareCodeDto.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
  backend/src/main/java/org/ftclub/cabinet/redis/ExpirationListener.java
  backend/src/main/java/org/ftclub/cabinet/redis/TicketingSharedCabinet.java
  backend/src/test/java/org/ftclub/cabinet/lent/domain/LentPolicyUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/redis/RedisRepositoryTest.java
  backend/src/test/resources/application.yml
  frontend/src/api/axios/axios.custom.ts
  frontend/src/assets/data/maps.ts
  frontend/src/assets/images/extensionTicket.svg
  frontend/src/components/AdminInfo/Chart/BarChart.tsx
  frontend/src/components/AdminInfo/Chart/PieChart.tsx
  frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CodeAndTime.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CountTime.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/AdminCabinetListItem.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Club/AdminClubLog.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/LeftNav/CabinetColorTable/CabinetColorTable.tsx
  frontend/src/components/MapInfo/MapItem/MapItem.tsx
  frontend/src/components/Modals/CancelModal/CancelModal.tsx
  frontend/src/components/Modals/ExtendModal/ExtendModal.tsx
  frontend/src/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
  frontend/src/components/SectionPagination/SectionPagination.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/recoil/atoms.ts
  frontend/src/types/dto/cabinet.dto.ts
  frontend/src/types/dto/user.dto.ts
  frontend/src/utils/dateUtils.ts
Labels: COMMON, CHALLENGE

#1353 [FE] 공유 사물함 대여 시 사물함 상태변화에 따라 CabinetListItem도 즉시 변경 되도록 수정
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CodeAndTime.tsx
  frontend/src/components/CabinetInfoArea/CountTime/CountTime.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
  frontend/src/components/MapInfo/MapItem/MapItem.tsx
  frontend/src/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/recoil/atoms.ts
  frontend/src/types/dto/cabinet.dto.ts
Labels: FE, CHALLENGE
