Repository innovationacademy-kr/Cabi, pull requests merged in 2023-04, with the labels that each got.

#1032 Exception을 처리하는 Controller추가
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionController.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/exception/ServiceException.java
Labels: BE, spring

#1031 주홍님, 동글리님, 훈진님 테스트 코드 공동 개발 (진행중), 서버 실행하면 JPA가 DDL 할 때 에러가 발생하는데 이를 수정
  .gitignore
  backend/.gitignore
  backend/build.gradle
  backend/build/classes/java/main/org/ftclub/cabinet/CabinetApplication.class
  backend/build/classes/java/main/org/ftclub/cabinet/admin/domain/AdminRole.class
  backend/build/classes/java/main/org/ftclub/cabinet/admin/domain/AdminUser.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/Cabinet.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/CabinetGrid.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/CabinetPlace.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/CabinetStatus.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/Grid.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/LentType.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/Location.class
  backend/build/classes/java/main/org/ftclub/cabinet/cabinet/domain/MapArea.class
  backend/build/classes/java/main/org/ftclub/cabinet/lent/domain/LentCabinetDetail.class
  backend/build/classes/java/main/org/ftclub/cabinet/lent/domain/LentHistory.class
  backend/build/classes/java/main/org/ftclub/cabinet/user/domain/BanHistory.class
  backend/build/classes/java/main/org/ftclub/cabinet/user/domain/BanType.class
  backend/build/classes/java/main/org/ftclub/cabinet/user/domain/User.class
  backend/build/classes/java/main/org/ftclub/cabinet/user/domain/UserRole.class
  backend/build/resources/main/application.yml
  backend/build/tmp/compileJava/compileTransaction/stash-dir/AdminUser.class.uniqueId1
  backend/build/tmp/compileJava/compileTransaction/stash-dir/BanHistory.class.uniqueId5
  backend/build/tmp/compileJava/compileTransaction/stash-dir/Cabinet.class.uniqueId6
  backend/build/tmp/compileJava/compileTransaction/stash-dir/CabinetPlace.class.uniqueId0
  backend/build/tmp/compileJava/compileTransaction/stash-dir/LentCabinetDetail.class.uniqueId4
  backend/build/tmp/compileJava/compileTransaction/stash-dir/LentHistory.class.uniqueId3
  backend/build/tmp/compileJava/compileTransaction/stash-dir/MapArea.class.uniqueId2
  backend/build/tmp/compileJava/compileTransaction/stash-dir/User.class.uniqueId7
  backend/build/tmp/compileJava/previous-compilation-data.bin
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetDto.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetPlace.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Grid.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetService.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
  backend/src/main/resources/application.yml
  backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetServiceTest.java
Labels: BE, SPRING_PORT

#1036 [BE] FEAT: JPA 및 DDL 업데이트
  .gitignore
  backend/build.gradle
  backend/src/main/java/org/ftclub/cabinet/admin/domain/AdminUser.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetGrid.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetPlace.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Grid.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Location.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/MapArea.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentCabinetDetail.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/org/ftclub/cabinet/CabinetApplicationTests.java
Labels: FEAT, BE, FIX, BE NEEDED

#1042 [BE] FIX: BANNED 타입 삭제로 인한 블랙홀 모듈 수정 #1041
  backend/src/admin/cabinet/cabinet.service.ts
  backend/src/admin/cabinet/repository/cabinet.repository.interface.ts
  backend/src/admin/cabinet/repository/cabinet.repository.ts
  backend/src/admin/dto/Overdue.user.cabinet.info.dto.ts
  backend/src/admin/dto/OverdueUserInfoPagenationDto.ts
  backend/src/admin/log/repository/log.repository.ts
  backend/src/admin/return/return.service.ts
  backend/src/blackhole/blackhole.service.ts
  backend/src/cabinet/cabinet.info.controller.ts
  backend/test/admin/cabinet.e2e-spec.ts
  backend/test/admin/search.e2e-spec.ts
  backend/test/main/cabinet.e2e-spec.ts
  backend/test/main/user.e2e-spec.ts
Labels: BE, FIX

#1049 [FE] FIX: 프론트엔드 dev to main을 위한 작업 #1048
  frontend/src/App.tsx
  frontend/src/assets/data/mapPositionData.ts
  frontend/src/components/CabinetList/CabinetList.container.tsx
  frontend/src/components/CabinetList/EmptySection/EmptySection.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/pages/admin/AdminLogPage.tsx
Labels: FE, v4, FIX

#1053 [FE] 캐비닛 받아오는 시점에서 cabi 이모티콘 뜨는 오류 #1052
  frontend/src/components/CabinetList/CabinetList.container.tsx
Labels: BUG, FE, v4

#1055 [FE] FIX: 3층 map 비활성화 -> 활성화로 변경 #1054
  frontend/src/assets/data/mapPositionData.ts
Labels: FE, FIX

#1058 [COMMON] cicd workflow 분리
  .github/workflows/backend-cicd.yaml
  .github/workflows/frontend-cicd.yaml
Labels: FIX, COMMON

#1060 dev to main 백엔드 핫픽스 및 프론트 에러 수정
  .github/workflows/backend-cicd.yaml
  .github/workflows/frontend-cicd.yaml
  backend/src/lent/lent.component.ts
  frontend/src/assets/data/mapPositionData.ts
  frontend/src/components/CabinetList/CabinetList.container.tsx
Labels: BUG, COMMON

#1062 [BE] SPRING FEAT : main, admin 인증 구현
  backend/build.gradle
  backend/src/main/java/org/ftclub/cabinet/CabinetApplication.java
  backend/src/main/java/org/ftclub/cabinet/auth/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/ApiUriBuilder.java
  backend/src/main/java/org/ftclub/cabinet/auth/AuthAspect.java
  backend/src/main/java/org/ftclub/cabinet/auth/AuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/AuthGuard.java
  backend/src/main/java/org/ftclub/cabinet/auth/CookieManager.java
  backend/src/main/java/org/ftclub/cabinet/auth/OauthService.java
  backend/src/main/java/org/ftclub/cabinet/auth/TokenProvider.java
  backend/src/main/java/org/ftclub/cabinet/auth/TokenValidator.java
  backend/src/main/java/org/ftclub/cabinet/auth/repository/AuthRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/config/DomainNameProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/FtApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/GoogleApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/JwtProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/SiteUrlProperties.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/exception/ServiceException.java
  backend/src/main/resources/application.yml
Labels: FEAT, BE, SPRING_PORT
