Repository innovationacademy-kr/Cabi, pull requests merged in 2023-06, with the labels that each got.

#1151 [FE] REFACTOR: LeftNav 리팩토링 #1137
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
  frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.container.tsx
Labels: REFACTOR, FE

#1149 [FE] REFACTOR: Cabinetlist, Userinfoarea 리팩토링/#1137
  frontend/src/components/CabinetList/CabinetList.container.tsx
  frontend/src/components/CabinetList/CabinetList.tsx
  frontend/src/components/CabinetList/CabinetListItem/AdminCabinetListItem.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/CabinetList/RealViewNotification/RealViewNotification.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.tsx
Labels: REFACTOR, FE, v4

#1150 [FE] REFACTOR: api, assets 폴더 리팩토링 #1137
  frontend/src/api/axios/axios.custom.ts
  frontend/src/api/axios/axios.instance.ts
  frontend/src/assets/css/mainPage.css
  frontend/src/assets/data/mapPositionData.ts
Labels: REFACTOR, FE

#1157 [FE] FIX: 어드민 사물함 검색 시 층 선택이 되도록 수정 #1155
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/TopNav/SearchBar/SearchBar.tsx
  frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
  frontend/src/pages/admin/SearchPage.tsx
Labels: FE, FIX

#1164 [FE] FIX: 어드민 사물함 검색 시 층 선택 되도록 수정 #1155
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/TopNav/SearchBar/SearchBar.tsx
  frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
  frontend/src/pages/admin/SearchPage.tsx
Labels: FE, FIX

#1163 [BE] SPRING 최고 관리자 권한, 로그인 구현 및 DB로 권한 확인 로직 추가
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthAspect.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthGuard.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/AuthLevel.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenProvider.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenValidator.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/AuthService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/config/DomainNameProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/MasterProperties.java
  backend/src/main/java/org/ftclub/cabinet/dto/MasterLoginDto.java
  backend/src/main/java/org/ftclub/cabinet/event/LentStartEvent.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/AdminRole.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/UserAspect.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/UserRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/controller/CabinetControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/AdminUserControllerTestSession.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/UserSessionControllerTest.java
  backend/src/test/java/org/ftclub/testutils/TestControllerUtils.java
Labels: FEAT, BE, SPRING_PORT

#1172 [BE] SPRING profile 오적용 문제 해결
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/CookieManager.java
  backend/src/main/java/org/ftclub/cabinet/config/DomainProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/FtApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/GoogleApiProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/JwtProperties.java
  backend/src/main/java/org/ftclub/cabinet/config/SiteUrlProperties.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
Labels: BE, FIX, SPRING_PORT

#1160 [FE] REFACTOR: Search 코드 리팩토링 #1137
  frontend/src/components/Search/NoSearch.tsx
  frontend/src/components/Search/SearchDefault.tsx
  frontend/src/components/Search/SearchItemByIntraId.tsx
  frontend/src/components/Search/SearchItemByNum.tsx
  frontend/src/pages/admin/SearchPage.tsx
Labels: REFACTOR, FE

#1165 [FE] REFACTOR: Home&Login 코드 리팩토링 #1137
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/Login/AdminLoginTemplate.tsx
  frontend/src/components/Login/LoginTemplate.tsx
  frontend/src/components/Login/__tests__/LoginTemplate.test.tsx
Labels: REFACTOR, FE

#1161 [FE] REFACTOR:TopNav 코드 리팩토링 #1137
  frontend/src/components/TopNav/AdminTopNav.container.tsx
  frontend/src/components/TopNav/SearchBar/SearchBarList/SearchBarList.tsx
  frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
  frontend/src/components/TopNav/TopNav.container.tsx
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
Labels: REFACTOR, FE

#1168 [BE] SPRING 로그아웃 구현
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AdminAuthControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/controller/AuthControllerTest.java
Labels: BE, SPRING_PORT

#1174 [BE] REFACTOR: CabinetInfoResponseDto 리팩토링 #1173
  backend/src/main/java/org/ftclub/cabinet/dto/CabinetWithMemoDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/MyCabinetResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
Labels: REFACTOR, BE, SPRING_PORT

#1176 [FE] REFACTOR:pages-hompage & loginpage 코드 리팩토링 #1137
  frontend/src/components/Login/AdminLoginTemplate.tsx
  frontend/src/components/Login/LoginTemplate.tsx
  frontend/src/components/Login/__tests__/LoginTemplate.test.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/admin/AdminLoginPage.tsx
Labels: REFACTOR, FE

#1169 [FE] REFACTOR: Mapinfo 코드 리팩토링 #1137
  frontend/src/components/MapInfo/MapGrid/MapGrid.tsx
  frontend/src/components/MapInfo/MapInfo.container.tsx
  frontend/src/components/MapInfo/MapInfo.tsx
  frontend/src/components/MapInfo/MapItem/MapItem.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/admin/AdminLayout.tsx
Labels: REFACTOR, FE

#1177 [FE] REFACTOR: main, adminMain 페이지 리팩토링#1137
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/admin/AdminMainPage.tsx
Labels: REFACTOR, FE, v4

#1181 [FE] REFACTOR: LentLog 컴포넌트에서 자주 쓰이는 ILentLog 를 lent.dto 에서 정의, constants 폴더 밑 StatusCode 생성 #1137
  frontend/src/api/axios/axios.instance.ts
  frontend/src/components/Error/ErrorTemplate.tsx
  frontend/src/components/LentLog/AdminCabinetLentLog.container.tsx
  frontend/src/components/LentLog/AdminCabinetLentLog.tsx
  frontend/src/components/LentLog/AdminUserLentLog.container.tsx
  frontend/src/components/LentLog/AdminUserLentLog.tsx
  frontend/src/components/LentLog/LentLog.container.tsx
  frontend/src/components/LentLog/LentLog.tsx
  frontend/src/components/LentLog/LogTable/AdminCabinetLogTable.tsx
  frontend/src/components/LentLog/LogTable/LogTable.tsx
  frontend/src/constants/StatusCode.ts
  frontend/src/pages/LogPage.tsx
  frontend/src/types/dto/lent.dto.ts
Labels: REFACTOR, FE, v4

#1170 [BE] SPRING Statistics API 구현
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/repository/StatisticsRepository.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/statistics/service/StatisticsServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/AdminUserControllerTest.java
Labels: FEAT, BE, SPRING_PORT

#1180 [BE] FIX: 대여, 반납 비관적 락으로 변경
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetExceptionHandlerService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetServiceTest.java
Labels: BE, FIX

#1186 [BE] FEAT: admin lent 추가
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetExceptionHandlerService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/dto/LentEndMemoDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/PaginationRequestDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UpdateCabinetMemoDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UpdateCabinetTitleDto.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/LentController.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
  backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/repository/StatisticsRepository.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
Labels: BE, SPRING_PORT

#1183 [FE] REFACTOR: MainPage의 swipeSection 함수 수정 #1137
  frontend/src/pages/MainPage.tsx
Labels: REFACTOR, FE

#1189 [BE] SPRING Cabinet 도메인 생성 로직 구현 및 ExceptionUtil 생성
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Cabinet.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetGrid.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/CabinetPlace.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Grid.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Location.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/MapArea.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/SectionFormation.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/utils/ExceptionUtil.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/domain/CabinetDomainTest.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/mapper/CabinetMapperTest.java
  backend/src/test/java/org/ftclub/cabinet/mapper/LentMapperTest.java
  backend/src/test/java/org/ftclub/cabinet/utils/ExceptionUtilTest.java
Labels: FEAT, BE, SPRING_PORT

#1185 [FE] REFACTOR: SectionPagination 및 CabinetInfoArea 리팩토링
  frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/SectionPagination/SectionPagination.container.tsx
  frontend/src/components/SectionPagination/SectionPagination.tsx
Labels: REFACTOR, FE, v4

#1192 [FE] REFACTOR: Modals 컴포넌트 리팩토링 및 추가 수정#1137
  frontend/src/components/LentLog/LogTable/AdminCabinetLogTable.tsx
  frontend/src/components/Modals/BanModal/BanModal.tsx
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/components/Modals/MemoModal/MemoModal.container.tsx
  frontend/src/components/Modals/MemoModal/MemoModal.tsx
  frontend/src/components/Modals/Modal.tsx
  frontend/src/components/Modals/ModalPortal.tsx
  frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.container.tsx
  frontend/src/components/Modals/PasswordCheckModal/PasswordCheckModal.tsx
  frontend/src/components/Modals/ResponseModal/ResponseModal.tsx
  frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.tsx
  frontend/src/components/Modals/UnavailableModal/UnavailableModal.tsx
  frontend/src/pages/LogPage.tsx
  frontend/src/types/dto/lent.dto.ts
Labels: REFACTOR, FE, v4

#1197 [BE] FIX: length -> size 변경 & totalLength -> totalPage
  backend/src/main/java/org/ftclub/cabinet/dto/BlockedUserPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/PaginationRequestDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UserProfilePaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
  backend/src/main/java/org/ftclub/cabinet/search/controller/SearchController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
Labels: BE, v4

#1200 [BE] FEAT, FIX: AuthFacadeService 구현 및 도메인 코드 수정, 관리자 권한 필요한 컨트롤러 @Au…
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AdminAuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenProvider.java
  backend/src/main/java/org/ftclub/cabinet/auth/domain/TokenValidator.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/AuthFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/AuthFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/AuthService.java
  backend/src/main/java/org/ftclub/cabinet/config/JwtProperties.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
  backend/src/main/java/org/ftclub/cabinet/search/controller/SearchController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenProviderTest.java
  backend/src/test/java/org/ftclub/cabinet/auth/domain/TokenValidatorTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserServiceTest.java
Labels: FEAT, BE, FIX, SPRING_PORT

#1195 [FE] REFACTOR: adminInfo를 adminHome 페이지로 이름 수정#1194
  frontend/src/App.tsx
  frontend/src/pages/admin/AdminHomePage.tsx
Labels: REFACTOR, FE, v4

#1201 [FE] fix: 현재 위치한 층과 동일한 맵 띄우기 #1133
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
  frontend/src/components/MapInfo/MapInfo.container.tsx
  frontend/src/recoil/atoms.ts
Labels: FE, FIX

#1207 [FE] BUG: AdminHomePage 에서 표가 모바일 환경에서 잘 보이게 조정과 변수명을 페이지명에 맞춰 변경 #1206
  frontend/src/pages/admin/AdminHomePage.tsx
Labels: BUG, FE, v4

#1208 [FE] feat:mapBackGround_floorInfo 추가
  frontend/src/assets/data/mapPositionData.ts
  frontend/src/components/MapInfo/MapItem/MapItem.tsx
Labels: FEAT, FE

#1214 [BE] FEAT: 실제 cabinet 데이터 추가
  backend/database/cabi_local.sql
  backend/database/init.sh
  backend/database/spring_test_db.sql
Labels: COMMON

#1215 [BE] FEAT: logger 추가
  backend/build.gradle
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/AdminCabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/AdminLentController.java
  backend/src/main/java/org/ftclub/cabinet/lent/controller/LentController.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentPolicyImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/search/controller/SearchController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/AdminUserController.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanPolicyImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/UserOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/main/resources/log4j2.xml
Labels: BE, v4

#1222 [BE] SPRING JoinColumn 적용
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/BanHistoryRepository.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/lent/service/LentServiceImplTest.java
  backend/src/test/java/org/ftclub/cabinet/mapper/UserSessionMapperTest.java
  backend/src/test/resources/application.yml
Labels: BE, FIX, SPRING_PORT

#1230 [BE] FIX : change Date type to LocalDateTime in statistics and Dto
  backend/src/main/java/org/ftclub/cabinet/dto/LentDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/LentHistoryDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/LentsStatisticsResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/MyProfileResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UserBlockedInfoDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UserSessionDto.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/main/java/org/ftclub/cabinet/statistics/controller/StatisticsController.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
Labels: BE, FIX
