Repository innovationacademy-kr/Cabi, pull requests merged in 2023-01, with the labels that each got.

#686 단일 사물함 정보 API response 값 추가 #676
  backend/src/cabinet/repository/cabinet.info.repository.ts
  backend/src/dto/response/cabinet.info.response.dto.ts
Labels: FEAT, BE

#694 [FE] FIX: Section Pagination 왼쪽바와 동기화, 기능부분 component로 분리 #691
  frontend_v4/src/components/SectionPagination.tsx
  frontend_v4/src/containers/SectionPaginationContainer.tsx
  frontend_v4/src/pages/MainPage.tsx
Labels: BUG, REFACTOR, FE, v4

#703 [FE] FIX: cabinet_info API 변경된 response 반영 #702
  frontend_v4/src/components/CabinetInfoArea.tsx
  frontend_v4/src/types/dto/cabinet.dto.ts
Labels: FE, v4, FIX

#709 [FE] FIX: pagination 바 로딩완료 체크 조건 추가 #706
  frontend_v4/src/components/SectionPagination.tsx
Labels: BUG, FE, v4

#707 [FE] FEAT: homeInfo "시작하기" 버튼 기능 추가, 파일이름 변경 #705
  frontend_v4/src/components/HomeInfo.tsx
  frontend_v4/src/containers/HomeInfoContainer.tsx
  frontend_v4/src/pages/HomePage.tsx
Labels: FEAT, REFACTOR, FE, v4

#711 [FE] FEAT: 모바일 환경을 위한 동작 구현 #663
  frontend_v4/src/assets/css/homePage.css
  frontend_v4/src/assets/css/loginPage.css
  frontend_v4/src/assets/css/mainPage.css
  frontend_v4/src/components/CabinetInfoArea.tsx
  frontend_v4/src/components/TopNav.tsx
  frontend_v4/src/containers/ButtonContainer.tsx
  frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
  frontend_v4/src/containers/CabinetListItemContainer.tsx
  frontend_v4/src/containers/HomeInfoContainer.tsx
  frontend_v4/src/containers/LeftNavAreaContainer.tsx
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/containers/LeftNavOptionContainer.tsx
  frontend_v4/src/containers/MapGridContainer.tsx
  frontend_v4/src/containers/MapInfoContainer.tsx
  frontend_v4/src/containers/TopNavButtonsContainer.tsx
  frontend_v4/src/containers/TopNavContainer.tsx
  frontend_v4/src/hooks/useDetailInfo.ts
  frontend_v4/src/hooks/useLeftNav.ts
  frontend_v4/src/index.css
  frontend_v4/src/media.css
  frontend_v4/src/pages/HomePage.tsx
  frontend_v4/src/pages/LoginPage.tsx
  frontend_v4/src/pages/MainPage.tsx
  frontend_v4/src/recoil/atoms.ts
Labels: FEAT, FE, v4, FIX

#697 [BE] FIX: 연체 관련 기능 향상
  backend/src/admin/cabinet/cabinet.controller.ts
  backend/src/lent/lent.component.ts
  backend/src/lent/repository/lent.repository.interface.ts
  backend/src/lent/repository/lent.repository.ts
  backend/src/utils/leave.absence.component.ts
  backend/src/utils/scheduling.component.ts
Labels: REFACTOR, BE, FIX

#715 [FE] REFACTOR: 공통 컴포넌트 Layout으로 분리
  frontend_v4/src/App.tsx
  frontend_v4/src/Layout.tsx
  frontend_v4/src/components/HomeInfo.tsx
  frontend_v4/src/components/TopNav.tsx
  frontend_v4/src/containers/LeftNavAreaContainer.tsx
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/containers/LeftNavOptionContainer.tsx
  frontend_v4/src/containers/SectionPaginationContainer.tsx
  frontend_v4/src/hooks/useDetailInfo.ts
  frontend_v4/src/pages/HomePage.tsx
  frontend_v4/src/pages/MainPage.tsx
Labels: REFACTOR, FE, v4

#717 [FE] login 버튼 클릭 시 로딩중 표시 #716
  frontend_v4/src/components/LoadingModal.tsx
  frontend_v4/src/index.css
  frontend_v4/src/pages/LoginPage.tsx
Labels: FEAT, FE, v4

#721 [FE] FIX: 홈에 [대여 시작하기] 버튼 이름 수정 + 기능 붙이기 #718
  frontend_v4/src/containers/HomeInfoContainer.tsx
Labels: FE, v4, FIX

#724 [FE] BUG: 로그아웃 버튼 클릭 시 login으로 네비게이팅 #723
  frontend_v4/src/containers/LeftNavContainer.tsx
Labels: BUG, FE, v4

#728 [FE] 모달창 배경 z-index 미적용 관련 오타 수정
  frontend_v4/src/containers/MemoModalContainer.tsx
  frontend_v4/src/containers/ModalContainer.tsx
Labels: BUG, FE, v4

#731 [FE] FEAT: 버튼 gary line 테마 추가 #730
  frontend_v4/src/containers/ButtonContainer.tsx
  frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
  frontend_v4/src/containers/MemoModalContainer.tsx
  frontend_v4/src/containers/ModalContainer.tsx
Labels: FEAT, FE, v4

#737 [FE] 내 사물함보기 버튼 기능 추가
  frontend_v4/src/components/TopNavButton.tsx
  frontend_v4/src/containers/TopNavButtonsContainer.tsx
  frontend_v4/src/hooks/useDetailInfo.ts
Labels: FEAT, FE, v4

#735 [FE] FIX: 대여 불가능한 사물함 우측 구역 출력 방지 #734
  frontend_v4/src/containers/CabinetListItemContainer.tsx
Labels: FE, v4, FIX

#733 [FE] FEAT: 우측 구역 취소 버튼 기능 추가 #683
  frontend_v4/src/components/CabinetInfoArea.tsx
Labels: FEAT, FE, v4

#746 [FE] FEAT: 404Page 추가 #745
  frontend_v4/src/App.tsx
  frontend_v4/src/assets/images/happyCcabi.png
  frontend_v4/src/assets/images/happyCcabiWhite.png
  frontend_v4/src/assets/images/sadCcabi.png
  frontend_v4/src/assets/images/sadCcabiWhite.png
  frontend_v4/src/media.css
  frontend_v4/src/pages/NotFoundPage.tsx
Labels: FEAT, FE, v4

#740 [FE] FEAT: 새로고침을 위한 recoil-persist 적용 #739
  frontend_v4/package-lock.json
  frontend_v4/package.json
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/recoil/atoms.ts
Labels: FEAT, FE, v4

#742 [FE] FIX: 불필요한 recoil 변수 삭제 #741
  frontend_v4/src/Layout.tsx
  frontend_v4/src/containers/LeftNavOptionContainer.tsx
  frontend_v4/src/containers/MapInfoContainer.tsx
  frontend_v4/src/hooks/useDetailInfo.ts
  frontend_v4/src/hooks/useLeftNav.ts
  frontend_v4/src/recoil/atoms.ts
Labels: FE, v4, FIX

#744 [FE] BUG: E/V클릭 후 pagination 이전버튼 클릭 버그 #743
  frontend_v4/src/components/SectionPagination.tsx
Labels: BUG, FE, v4

#748 [FE] 대여, 반납 api
  frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
  frontend_v4/src/containers/CabinetListItemContainer.tsx
  frontend_v4/src/containers/ModalContainer.tsx
  frontend_v4/src/containers/TopNavButtonsContainer.tsx
  frontend_v4/src/recoil/atoms.ts
Labels: FEAT, FE, v4

#751 [FE] BUG: 대여, 반납 후 캐비넷 정보, 상세정보 미반영 버그 #750
  frontend_v4/src/components/TopNav.tsx
  frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/hooks/useIsMount.ts
  frontend_v4/src/recoil/atoms.ts
Labels: BUG, FEAT, FE, v4

#758 [FE] FEAT: 화면에 보이는 사물함 위치가 실제와 다를 때 알림
  frontend_v4/src/assets/images/cautionSign.png
  frontend_v4/src/components/CabinetList.tsx
  frontend_v4/src/components/RealViewNotification.tsx
  frontend_v4/src/containers/SectionPaginationContainer.tsx
Labels: FEAT, FE, v4

#764 [FE] FIX: import 경로 파일이름 수정 #747
  frontend_v4/src/containers/MapInfoContainer.tsx
Labels: BUG, FE, v4

#762 [FE] 캐비넷 메모, 타이틀 수정 api적용
  frontend_v4/src/components/MemoModal.tsx
  frontend_v4/src/containers/MemoModalContainer.tsx
Labels: FEAT, FE, v4

#761 [FE] FEAT: 캐비넷 선택시 호버효과 고정 적용 #722
  frontend_v4/src/components/CabinetInfoArea.tsx
  frontend_v4/src/containers/CabinetListItemContainer.tsx
Labels: FEAT, FE, v4

#772 [FE] BUG: 사파리에서 메모 수정하기 버튼이 잘려보이는 이슈 해결 #771
  frontend_v4/src/containers/MemoModalContainer.tsx
  frontend_v4/src/index.css
Labels: BUG, FE

#768 [FE] REFACTOR: 대여 반납 api호출부 모듈화 #763
  frontend_v4/src/components/Modal.tsx
  frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
  frontend_v4/src/containers/ModalContainer.tsx
  frontend_v4/src/maps.ts
Labels: REFACTOR, FE, v4

#774 [FE] 메모 모달안의 수정하기 클릭 시 input필드 autoFocus 적용 #773
  frontend_v4/src/containers/MemoModalContainer.tsx
Labels: FE, FIX

#775 [FE] FIX: 사물함 위치가 실제 위치랑 다르게 보일 때의 아이콘 수정 #757
  frontend_v4/src/assets/images/cautionSign.png
  frontend_v4/src/assets/images/cautionSign.svg
  frontend_v4/src/components/RealViewNotification.tsx
Labels: FE, v4, FIX

#777 [FE] FEAT: 페이지네이션 스크롤 시 상단 고정 #776
  frontend_v4/src/containers/SectionPaginationContainer.tsx
Labels: FEAT, FE, v4

#783 [FE] FIX: 우측 지도 구역 z-index 10으로 조정 #782
  frontend_v4/src/containers/MapInfoContainer.tsx
Labels: FE, v4, FIX

#785 [FE] BUG: 맵에서 다른 층의 섹션을 선택했을 때의 버그 수정 #765
  frontend_v4/src/components/Modal.tsx
  frontend_v4/src/containers/LeftNavContainer.tsx
  frontend_v4/src/containers/MapGridContainer.tsx
  frontend_v4/src/recoil/atoms.ts
Labels: BUG, FE, v4

#784 [FE] FIX: 페이지네이션 바 z-index 1로 조정, 우측 구역 9로 복구 #782
  frontend_v4/src/containers/MapInfoContainer.tsx
  frontend_v4/src/containers/SectionPaginationContainer.tsx
Labels: FE, v4, FIX

#788 [FE] FEAT: 슬랙문의, 사물함 신청 링크 추가하기 #787
  frontend_v4/index.html
  frontend_v4/src/assets/images/circleIconGray.svg
  frontend_v4/src/assets/images/slack.svg
  frontend_v4/src/containers/LeftNavContainer.tsx
Labels: FEAT, FE, v4

#781 [FE] FEAT: 이미 대여 중일 때 대여 버튼 클릭 방지, gray 테마 버튼 추가 #760
  frontend_v4/src/components/CabinetInfoArea.tsx
  frontend_v4/src/containers/ButtonContainer.tsx
  frontend_v4/src/containers/CabinetInfoAreaContainer.tsx
  frontend_v4/src/containers/MemoModalContainer.tsx
Labels: FEAT, FE, v4

#798 [FE] FIX: 메모 모달 포탈 적용, CD 명령어 수정 #797
  backend/package.json
  frontend/src/components/Modals/MemoModal/MemoModal.tsx
Labels: SETTING, FE, v4

#802 [FE] FIX: 모바일에서 터치 이후 hover css 적용되는 문제 #801
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/CabinetList/RealViewNotification/RealViewNotification.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
  frontend/src/components/MapInfo/MapFloorSelect/MapFloorSelect.tsx
  frontend/src/components/MapInfo/MapGrid/MapGrid.tsx
  frontend/src/components/SectionPagination/SectionPagination.tsx
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButton/TopNavButton.tsx
  frontend/src/index.css
Labels: FE, v4, FIX

#804 [FE] FIX: 다크모드 css 삭제 #803
  frontend/src/index.css
Labels: FE, v4, FIX

#808 [FE] FIX: 사물함 상세보기 모바일 크기 적용 #807
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Modals/MemoModal/MemoModal.tsx
  frontend/src/pages/Layout.tsx
Labels: FE, v4, FIX

#806 [FE] FIX: mapInfo 폴더의 컴포넌트, 데이터 분리 및 CSS 조정 #805
  frontend/src/assets/data/mapPositionData.ts
  frontend/src/components/MapInfo/MapFloorSelect/MapFloorSelect.tsx
  frontend/src/components/MapInfo/MapFloorSelectOption/MapFloorSelectOption.tsx
  frontend/src/components/MapInfo/MapGrid/MapGrid.tsx
  frontend/src/components/MapInfo/MapInfo.tsx
  frontend/src/components/MapInfo/MapItem/MapItem.tsx
Labels: REFACTOR, FE, v4, FIX

#813 [FE] FIX: 모바일 섹션 스와이프 기능 파일 위치 수정 #796
  frontend/src/pages/Layout.tsx
  frontend/src/pages/MainPage.tsx
Labels: FE, v4, FIX

#816 [BE] TEST: cabinet 테스트 병합 #793
  backend/package.json
  backend/src/admin/auth/auth.controller.ts
  backend/src/admin/auth/google/guard/google.guard.ts
  backend/src/admin/auth/jwt/guard/jwtsign.guard.ts
  backend/src/admin/cabinet/cabinet.controller.ts
  backend/src/admin/return/return.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/cabinet/cabinet.info.service.spec.ts
  backend/src/cabinet/repository/mock/mock.cabinet.info.repository.ts
  backend/src/user/my.lent.info.controller.ts
Labels: FEAT, BE

#811 [BE] FEAT: 서울 카뎃만 42 인증이 가능하게끔 기능 및 문구 추가 #738
  backend/src/auth/42/ft.strategy.ts
  backend/src/auth/42/guard/ft.guard.ts
Labels: FEAT, BE

#820 [FE] FEAT: 모바일 환경에서의 오류 수정 및 기능 추가 #817
  backend/package.json
  frontend/index.html
  frontend/src/assets/css/media.css
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/LeftNav/LeftNav.tsx
  frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
  frontend/src/components/MapInfo/MapInfo.tsx
  frontend/src/components/MapInfo/MapItem/MapItem.tsx
  frontend/src/components/TopNav/TopNav.container.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/hooks/useDetailInfo.ts
  frontend/src/hooks/useLeftNav.ts
  frontend/src/hooks/useMenu.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/Layout.tsx
Labels: FEAT, REFACTOR, FE, v4, FIX

#810 [FE] 제목 없는 공유 사물함 메모 모달에서 제목 박스가 안보이던 버그 수정 #809
  frontend/src/components/Modals/MemoModal/MemoModal.tsx
Labels: BUG, FE, v4, FIX

#821 [FE] BUG: 내 사물함 보기 클릭 시 깜빡임 증상 처리 #817
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/hooks/useMenu.ts
Labels: BUG, FE, v4

#823 [FE] BUG: 뒤로가기, 앞으로가기 시, 캐비닛정보를 못받아오는 이슈 #814
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/pages/HomePage.tsx
Labels: BUG, FE, v4

#824 [FE] 라우터 이동 시 recoil 값 초기화 안되는 버그 #822
  frontend/src/pages/HomePage.tsx
Labels: BUG, FE, v4

#830 [FE] FIX: img src 절대경로로 수정 #828
  frontend/src/App.tsx
  frontend/src/assets/data/maps.ts
  frontend/src/components/CabinetList/RealViewNotification/RealViewNotification.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/pages/LoginPage.tsx
Labels: FE, v4, FIX

#852 [FE] FIX: 타이틀 및 메모 첫 수정시 수정사항 미반영 이슈 해결 #851
  frontend/src/components/Modals/MemoModal/MemoModal.container.tsx
Labels: BUG, FE, v4

#839 [FE] FEAT: 이스터 에그 추가 #838
  frontend/src/components/CabinetList/CabinetList.container.tsx
  frontend/src/components/CabinetList/EmptySection.tsx
Labels: FEAT, FE, v4

#845 [FE] FIX: 지도 컴포넌트 스와이프 이벤트 방향 수정 #835
  frontend/src/components/MapInfo/MapInfo.container.tsx
Labels: FE, v4, FIX

#856 [FE] 아이폰 메모 수정모드 진입 시 키보드 활성화가 안되던 이슈 해결 #853
  frontend/src/components/Modals/MemoModal/MemoModal.tsx
Labels: BUG, FE, v4

#857 [BE] REFACTOR: enum 타입 이름 중 CIRCLE을 CLUB으로 변경 #855
  backend/database/42cabi_v3_test.sql
  backend/database/42cabi_v4_test.sql
  backend/src/admin/dto/cabinet.dto.ts
  backend/src/admin/dto/lent.cabinet.data.dto.ts
  backend/src/dto/cabinet.dto.ts
  backend/src/enums/lent.exception.enum.ts
  backend/src/enums/lent.type.enum.ts
  backend/src/lent/lent.component.ts
  backend/src/lent/lent.service.ts
Labels: REFACTOR, BE

#819 [BE] FEAT: 외국 카뎃 로그인에 따른 리디렉션 및 로거 추가 #793
  backend/src/admin/auth/auth.controller.ts
  backend/src/admin/auth/google/guard/google.guard.ts
  backend/src/admin/auth/jwt/guard/jwtsign.guard.ts
  backend/src/admin/cabinet/cabinet.controller.ts
  backend/src/admin/return/return.module.ts
  backend/src/auth/42/ft.auth.filter.ts
  backend/src/auth/42/ft.strategy.ts
  backend/src/auth/42/guard/ft.guard.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/user/my.lent.info.controller.ts
Labels: FEAT, BE, FE NEEDED

#844 [BE] FEAT: admin 로그인 실패시 리디렉션 및 로거 추가 #834
  backend/src/admin/auth/auth.controller.ts
  backend/src/admin/auth/google/google.auth.filter.ts
  backend/src/admin/auth/jwt/guard/jwtsign.guard.ts
Labels: BUG, FEAT, BE, FE NEEDED

#841 [FE] 외국 카뎃 로그인에 따른 /login/failure 페이지 추가 #840
  frontend/src/App.tsx
  frontend/src/assets/css/media.css
  frontend/src/components/Error/ErrorTemplate.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/LoginFailurePage.tsx
  frontend/src/pages/NotFoundPage.tsx
Labels: FEAT, FE, v4

#850 [FE] REFACTOR: 왼쪽 nav 컨테이너, 컴포넌트 분리 작업 #846
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/components/LeftNav/LeftNav.tsx
  frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.container.tsx
  frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
Labels: REFACTOR, FE, v4

#864 [FE] FIX: CIRCLE 단어 CLUB 으로 교체 #860
  frontend/src/assets/data/maps.ts
  frontend/src/assets/images/clubIcon.svg
  frontend/src/assets/images/clubIconGray.svg
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/types/enum/cabinet.type.enum.ts
Labels: FE, v4, FIX

#872 [FE] BUG: 층 바꿀 때마다 cabi 캐릭터 보이는 버그 #871
  frontend/src/components/CabinetList/CabinetList.container.tsx
  frontend/src/components/CabinetList/CabinetList.tsx
  frontend/src/components/CabinetList/EmptySection/EmptySection.tsx
Labels: BUG, FE, v4

#876 [BE] FEAT: 어드민 유저 일반 어드민으로 승격 API 구현 #870
  backend/src/admin/admin.module.ts
  backend/src/admin/auth/google/google.auth.filter.ts
  backend/src/admin/develop/develop.controller.ts
  backend/src/admin/develop/develop.module.ts
  backend/src/admin/develop/develop.service.ts
  backend/src/admin/develop/repository/develop.repository.interface.ts
  backend/src/admin/develop/repository/develop.repository.ts
  backend/src/auth/42/ft.auth.filter.ts
  backend/src/config/configuration.ts
Labels: FEAT, BE, FE NEEDED

#883 [BE] FEAT : cabinet/count/floor 구현 #879
  backend/src/admin/cabinet/cabinet.controller.ts
  backend/src/admin/cabinet/cabinet.service.ts
Labels: FEAT, BE

#886 [BE] FIX : CabinetFloorDto 임포트수정 #879
  backend/src/admin/cabinet/cabinet.controller.ts
Labels: BUG, BE, FIX

#882 [BE] FIX : LentLog 반환시 return_time을 기준으로 내림차순으로 가져오도록 변경 #881
  backend/src/admin/log/repository/log.repository.ts
Labels: BE, FIX, FE NEEDED

#880 [BE] FEAT: admin, main 둘 중 하나라도 토큰이 존재하는 경우 auth 해주는 가드 구현
  backend/src/auth/jwt/guard/admin.main.jwtauth.guard.ts
Labels: FEAT, BE, FE NEEDED

#889 [BE] BUG : Devleop 모듈 로딩 안되는 문제 수정 - ConfigModule import #888
  backend/src/admin/admin.module.ts
Labels: BUG, BE

#893 [FE] 루트로 접근 시 login으로 리다이렉션되면서 Nav 보이는 버그 #892
  frontend/src/components/LeftNav/LeftNav.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/admin/AdminLayout.tsx
Labels: BUG, FE, v4

#895 [FE] FEAT: V4 배포 전 기능 개선, 버그 수정 #894
  backend/src/ban/guard/ban-check.guard.ts
  backend/src/lent/lent.service.ts
  frontend/index.html
  frontend/src/assets/data/maps.ts
  frontend/src/assets/images/desktopLogo.png
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/components/MapInfo/MapInfo.container.tsx
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/components/Modals/MemoModal/MemoModal.tsx
  frontend/src/components/Modals/ResponseModal/ResponseModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
  frontend/src/pages/MainPage.tsx
Labels: FEAT, FE, v4, FIX

#899 [BE] HOTFIX: update title, memo에 class-validate 추가 #898
  backend/src/dto/request/update.cabinet.memo.request.dto.ts
  backend/src/dto/request/update.cabinet.title.request.dto.ts
Labels: BE

#900 [BE] HOTFIX : Exception 메시지 변경 #897
  backend/src/admin/auth/jwt/guard/jwtauth.guard.ts
  backend/src/admin/cabinet/cabinet.service.ts
  backend/src/admin/develop/develop.controller.ts
  backend/src/admin/log/log.service.ts
  backend/src/admin/return/return.service.ts
  backend/src/auth/jwt/guard/admin.main.jwtauth.guard.ts
  backend/src/auth/jwt/guard/jwtauth.guard.ts
  backend/src/ban/guard/ban.check.guard.ts
  backend/src/cabinet/cabinet.info.service.spec.ts
  backend/src/cabinet/cabinet.info.service.ts
  backend/src/lent/lent.controller.ts
  backend/src/lent/lent.service.ts
Labels: BE, FIX

#913 [FE] BUG: 삼성 인터넷 앱 블루 하이라이트 버그 수정 #905
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/index.css
Labels: BUG, FE, v4
