Repository innovationacademy-kr/Cabi, pull requests merged in 2023-02, with the labels that each got.

#918 [FE] frontend 유닛 테스팅을 위한 vitest 설치 및 초기설정 #891
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Login/__tests__/LoginTemplate.test.tsx
  frontend/src/setupTest.ts
  frontend/vite.config.ts
Labels: SETTING, FE

#922 [BE] 어드민 페이지 검색 시 검색된 유저의 대여 정보 받아오는 API 구현 #921
  backend/src/admin/dto/cabinet.info.dto.ts
  backend/src/admin/dto/user.cabinet.info.dto.ts
  backend/src/admin/dto/user.cabinet.info.pagenation.dto.ts
  backend/src/admin/search/repository/search.repository.interface.ts
  backend/src/admin/search/repository/search.repository.ts
  backend/src/admin/search/search.controller.ts
  backend/src/admin/search/search.service.ts
Labels: FEAT, BE

#670 고립수준 낮추고, 공용사물함에 정해진 인원보다 많은 인원이 대여하게 되는 문제 해결
  backend/src/ban/ban.service.ts
  backend/src/ban/repository/ban.repository.ts
  backend/src/blackhole/blackhole.service.ts
  backend/src/cabinet/cabinet.info.service.ts
  backend/src/cabinet/repository/cabinet.info.repository.ts
  backend/src/dto/lent.cabinet.data.dto.ts
  backend/src/entities/lent.entity.ts
  backend/src/lent/lent.component.ts
  backend/src/lent/lent.controller.ts
  backend/src/lent/repository/lent.repository.interface.ts
  backend/src/lent/repository/lent.repository.ts
  backend/src/user/repository/user.repository.ts
  backend/src/user/user.service.ts
  backend/src/utils/expired.checker.component.ts
Labels: BE, v3, FIX

#935 [BE] 각각의 테스트 파일들이 병렬적으로 실행될 수 있도록 수정
  backend/test/admin/lent.e2e-spec.ts
  backend/test/main/lent.e2e-spec.ts
  backend/test/utils.ts
Labels: BUG, BE

#936 Be/dev/e2e test main lent/#793
  backend/test/test_db.sql
Labels: BE

#938 [BE] FIX: searchUserCabinetList에서 정렬 조건 수정 #921
  backend/src/admin/search/repository/search.repository.ts
Labels: BUG, BE

#927 [FE] FIX: 차트 색상 및 데이터 출력 값 수정 #926
  frontend/src/components/AdminChart/BarChart.tsx
  frontend/src/components/AdminChart/PieChart.tsx
  frontend/src/components/Login/LoginTemplate.tsx
Labels: FE, v4, FIX

#932 [FE] FEAT: location 선택 버튼 useOutsideClick hook 적용 #931
  frontend/index.html
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/hooks/useOutsideClick.ts
Labels: FEAT, FE, v4, FIX

#934 [FE] FEAT: 모바일을 위한 검색 레이아웃 수정 #933
  frontend/src/assets/css/media.css
  frontend/src/components/TopNav/SearchBar/SearchBar.tsx
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
Labels: FEAT, FE, v4

#941 [COMMON] versioning prefix 제거 #940
  .gitignore
  backend/database/42cabi_v3_test.sql
  backend/database/cabi_local.sql
  backend/database/init.sh
  backend/docker-compose.yaml
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/configuration.ts
  backend/src/config/typeorm.config.ts
  dev/configure.conf
  frontend/package.json
Labels: COMMON

#937 [BE] lent, return e2e test 코드 작성 #793
  backend/package-lock.json
  backend/package.json
  backend/src/admin/lent/lent.controller.ts
  backend/src/admin/return/return.controller.ts
  backend/test/admin/lent.e2e-spec.ts
  backend/test/admin/return.e2e-spec.ts
  backend/test/main/lent.e2e-spec.ts
  backend/test/test_db.sql
Labels: BE, TEST

#947 user lent e2e test 작성
  .gitignore
  backend/package-lock.json
  backend/test/admin/cabinet.e2e-spec.ts
  backend/test/main/user.e2e-spec.ts
Labels: BE, TEST

#946 [BE] TEST: lent, return 테스트 보강 #793
  backend/test/admin/lent.e2e-spec.ts
  backend/test/admin/return.e2e-spec.ts
  backend/test/main/lent.e2e-spec.ts
Labels: BE, TEST

#948 [FE] FEAT: 관리자 메인 페이지 반응형 구현 #928
  frontend/src/components/AdminChart/AdminChart.tsx
  frontend/src/components/AdminChart/BarChart.tsx
  frontend/src/components/AdminChart/Pagination.tsx
  frontend/src/components/AdminChart/PieChart.tsx
  frontend/src/components/AdminPreview/ActivationTable.tsx
  frontend/src/components/AdminPreview/AdminPreview.tsx
  frontend/src/components/AdminPreview/BanTable.tsx
  frontend/src/pages/admin/AdminHomePage.tsx
  frontend/src/pages/admin/AdminPagination.tsx
  frontend/src/types/dto/lent.dto.ts
Labels: FEAT, FE, v4

#944 [FE] FEAT: 검색바 UX 개선 #943
  frontend/src/api/axios/axios.custom.ts
  frontend/src/assets/css/media.css
  frontend/src/components/Search/SearchItemByIntraId.tsx
  frontend/src/components/Search/SearchItemByNum.tsx
  frontend/src/components/TopNav/SearchBar/SearchBar.tsx
  frontend/src/components/TopNav/SearchBar/SearchBarList/SearchBarList.tsx
  frontend/src/components/TopNav/SearchBar/SearchListItem/SearchListItem.tsx
  frontend/src/hooks/useMenu.ts
  frontend/src/pages/admin/SearchPage.tsx
  frontend/src/recoil/atoms.ts
Labels: FEAT, FE, v4

#953 [BE] 사물함 번호로 검색 API에서 층 정보를 받도록 수정
  backend/src/admin/search/repository/search.repository.interface.ts
  backend/src/admin/search/repository/search.repository.ts
  backend/src/admin/search/search.controller.ts
  backend/src/admin/search/search.service.ts
Labels: BE, FIX

#951 Be/e2e test/admin develop/#793
  backend/test/admin/cabinet.e2e-spec.ts
  backend/test/admin/develop.e2e-spec.ts
Labels: FEAT, BE

#954 [BE] TEST : admin, main cabinet 테스트 코드 #793
  backend/test/admin/cabinet.e2e-spec.ts
  backend/test/main/cabinet.e2e-spec.ts
Labels: BE, TEST

#968 [FE] admin이 단일 선택모드에서 개인 캐비닛 반납 클릭 시 반납 모달 렌더링 및 api연동
  frontend/src/api/axios/axios.custom.ts
  frontend/src/assets/data/maps.ts
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
  frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
  frontend/src/recoil/atoms.ts
Labels: FEAT, FE, v4

#963 [BE] feat: 특정 유저의 페널티 해제 기능 추가 #960
  backend/src/admin/log/log.controller.ts
  backend/src/admin/log/log.service.ts
  backend/src/admin/log/repository/log.interface.repository.ts
  backend/src/admin/log/repository/log.repository.ts
Labels: FEAT, BE

#970 [BE] FIX: admin search intraId에 대여정보와 사용정지 정보 추가 #961
  backend/src/admin/dto/blocked.user.info.dto.ts
  backend/src/admin/dto/cabinet.location.floor.dto.ts
  backend/src/admin/dto/user.cabinet.info.dto.ts
  backend/src/admin/search/repository/search.repository.ts
Labels: BE, FIX

#964 [BE] FEAT : admin에서 대여 및 반납 일정 기간 횟수 통계값 반환 구현 #962
  backend/src/admin/dto/admin.statstics.dto.ts
  backend/src/admin/search/repository/search.repository.interface.ts
  backend/src/admin/search/repository/search.repository.ts
  backend/src/admin/search/search.controller.ts
  backend/src/admin/search/search.module.ts
  backend/src/admin/search/search.service.ts
Labels: FEAT, BE

#967 /api/admin/search/user/banned API 수정 완료
  backend/src/admin/dto/blocked.user.cabinet.info.dto.ts
  backend/src/admin/dto/blocked.user.info.pagenation.dto.ts
  backend/src/admin/search/repository/search.repository.interface.ts
  backend/src/admin/search/repository/search.repository.ts
  backend/src/admin/search/search.controller.ts
  backend/src/admin/search/search.module.ts
  backend/src/admin/search/search.service.ts
Labels: BE, FIX

#975 [FE] admin 공유 사물함 반납 기능 추가
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/Common/PillButton.tsx
  frontend/src/components/Common/Selector.tsx
  frontend/src/components/Modals/Modal.tsx
  frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
Labels: FEAT, FE, v4

#979 [FE] FEAT: 유저 상세정보 컴포넌트, 밴 해제 모달 추가 #957 #958
  frontend/src/api/axios/axios.custom.ts
  frontend/src/assets/data/maps.ts
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetList/CabinetListItem/AdminCabinetListItem.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Modals/BanModal/BanModal.tsx
  frontend/src/components/Search/SearchItemByIntraId.tsx
  frontend/src/components/Search/SearchItemByNum.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.tsx
  frontend/src/hooks/useMenu.ts
  frontend/src/pages/admin/AdminLayout.tsx
  frontend/src/pages/admin/SearchPage.tsx
  frontend/src/recoil/atoms.ts
  frontend/src/types/dto/user.dto.ts
Labels: FEAT, FE, v4
