Repository innovationacademy-kr/Cabi, pull requests merged in 2023-11, with the labels that each got.

#1423 [FE} FIX: 프로필 페이지 버그, 가시성, UX 수정 #1415
  README.md
  frontend/index.html
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/Card/Card.tsx
  frontend/src/components/Card/CardStyles.ts
  frontend/src/components/Card/LentInfoCard/LentInfoCard.container.tsx
  frontend/src/components/Card/LentInfoCard/LentInfoCard.tsx
  frontend/src/components/Card/ThemeColorCard/ThemeColorCard.tsx
  frontend/src/components/Common/ToggleSwitch.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/Modals/ExtendModal/ExtendModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
  frontend/src/components/Search/SearchItemByIntraId.tsx
  frontend/src/components/Search/SearchItemByNum.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/hooks/useCabinetListRefresh.ts
  frontend/src/index.css
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/admin/AdminLoginPage.tsx
  frontend/src/pages/admin/AdminMainPage.tsx
  maintenance/index.html
Labels: FE, v4, FIX

#1426 Be/dev/feat get pending cabinets/#1421
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/dto/CabinetPendingResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/mapper/CabinetMapper.java
Labels: FEAT, BE

#1449 [FE] FIX: 프로필 페이지에서 알림 카드 제거 #1447
  frontend/src/pages/ProfilePage.tsx
Labels: FE, v4, HOTFIX

#1454 [FE] FEAT: pendingPage refresh 버튼 추가 및 useDebounce 훅 추가
  frontend/src/assets/images/refresh.svg
  frontend/src/hooks/useDebounce.tsx
  frontend/src/pages/PendingPage/PendingPage.tsx
Labels: FEAT, FE

#1455 [FE] FIX: 연체 시 프로필 페이지에서 연체 기간을 표시하도록 수정 #1453
  frontend/src/components/Card/CardStyles.ts
  frontend/src/components/Card/LentInfoCard/LentInfoCard.container.tsx
  frontend/src/components/Card/LentInfoCard/LentInfoCard.tsx
Labels: FEAT, FE, v4

#1460 [BE] 연장권 삭제 로직 변경 및 변경에 따른 조회 로직 수정
  backend/database/cabi_local.sql
  backend/src/main/java/org/ftclub/cabinet/dto/LentExtensionResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/LentExtension.java
  backend/src/main/java/org/ftclub/cabinet/user/repository/LentExtensionOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/user/controller/UserControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/LentExtensionServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/UserFacadeServiceTest.java
Labels: BE, FIX
