Repository innovationacademy-kr/Cabi, pull requests merged in 2023-03, with the labels that each got.

#987 [FE] admin 사물함 상태 관리 모달 추가
  frontend/src/api/axios/axios.custom.ts
  frontend/src/assets/data/maps.ts
  frontend/src/assets/images/dropdownChevron.svg
  frontend/src/assets/images/warningTriangleIcon.svg
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/Common/Dropdown.tsx
  frontend/src/components/Common/WarningNotification.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.tsx
Labels: FEAT, FE, v4

#994 [FE] FEAT: 관리자 메인 페이지 구현 #985
  backend/database/cabi_local.sql
  frontend/src/components/AdminInfo/AdminDetailInfo.tsx
  frontend/src/components/AdminInfo/Table/AdminTable.tsx
  frontend/src/components/AdminInfo/convertFunctions.ts
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetList/CabinetList.tsx
  frontend/src/components/Modals/BanModal/BanModal.tsx
  frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
  frontend/src/hooks/useFetchData.ts
  frontend/src/pages/admin/AdminInfoPage.tsx
  frontend/src/recoil/atoms.ts
  frontend/src/types/dto/admin.dto.ts
Labels: FEAT, FE, v4

#1000 [FE] admin 사물함 일괄반납, 일괄 상태 관리 기능 추가
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/Modals/Modal.tsx
  frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.tsx
  frontend/src/hooks/useMultiSelect.ts
Labels: FEAT, FE, v4

#1007 [BE] BUG: 어드민 로그 페이지네이션 비정상 작동 수정#1004
  backend/src/admin/log/repository/log.repository.ts
Labels: BUG, BE, FIX

#1008 [BE] BUG: 캐비닛 렌트 타입 변경시 max_user 변경 반영 #1005
  backend/src/admin/cabinet/cabinet.service.ts
  backend/src/admin/cabinet/repository/cabinet.repository.interface.ts
  backend/src/admin/cabinet/repository/cabinet.repository.ts
Labels: BUG, FEAT, BE, FIX

#1010 [BE] FIX: 장기 연체시 강제 반납 로직 삭제
  backend/src/utils/email.sender.component.ts
  backend/src/utils/expired.checker.component.ts
  backend/src/utils/templates/overdue.hbs
  backend/src/utils/templates/soonoverdue.hbs
Labels: BE, FIX

#1002 [FE] FEAT: 검색 페이지 - 상세정보란 관리자 모달 연결, 사물함 반납 버튼 비활성화 조건 추가 #999
  frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/Modals/ReturnModal/AdminReturnModal.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.tsx
  frontend/src/recoil/atoms.ts
Labels: FEAT, FE, v4

#1011 [FE] 다중선택모드에서 일괄 상태변경 시 변경사항이 모달에 반영 안되는 버그 수정 #1006
  frontend/src/components/Common/Dropdown.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
  frontend/src/components/Modals/StatusModal/StatusModal.tsx
  frontend/src/hooks/useMultiSelect.ts
Labels: BUG, FE, v4

#1014 [FE] 다중선택 모드에서 사물함 일괄반납 시 저장 버튼 비활성화 여부 체크 로직 추가 #1013
  frontend/src/components/Modals/StatusModal/StatusModal.container.tsx
Labels: BUG, FE, v4

#1019 [FE] HOTFIX: 3층 맵 정보 추가 #1018
  frontend/src/assets/data/mapPositionData.ts
Labels: FEAT, FE, v4

#1020 장기 대여 사물함 타입 추가
  backend/database/cabi_local.sql
  backend/src/enums/lent.exception.enum.ts
  backend/src/enums/lent.type.enum.ts
  backend/src/lent/lent.component.ts
  backend/src/lent/lent.controller.ts
  backend/src/lent/lent.service.ts
  frontend/src/assets/css/homePage.css
  frontend/src/assets/data/maps.ts
  frontend/src/assets/data/sectionColNumData.ts
  frontend/src/assets/images/longTermIcon.svg
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
  frontend/src/types/enum/cabinet.type.enum.ts
Labels: FEAT, COMMON

#1025 [FE] BUG: 공유 사물함 대여 시작 되기 전에는 날짜가 나오지 않도록 수정 #1024
  backend/package-lock.json
  frontend/src/components/Modals/LentModal/LentModal.tsx
  frontend/src/components/Modals/ReturnModal/ReturnModal.tsx
Labels: BUG, FE, v4

#1027 [FE] FIX: 장기 대여 사물함 롤백, 오타 수정 #1026
  frontend/src/assets/css/homePage.css
  frontend/src/assets/data/maps.ts
  frontend/src/assets/images/longTermIcon.svg
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.container.tsx
  frontend/src/components/CabinetInfoArea/CabinetInfoArea.tsx
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Home/ServiceManual.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.container.tsx
  frontend/src/types/enum/cabinet.type.enum.ts
Labels: FE, v4, FIX
