Repository innovationacademy-kr/Cabi, pull requests merged in 2023-12, with the labels that each got.

#1466 [BE] pending 조회 로직 수정 및 cabinet, lent 리팩토링
  backend/src/main/java/org/ftclub/cabinet/cabinet/controller/CabinetController.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetComplexRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/firebase/FCMInitializer.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentOptionalFetcher.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceImpl.java
  backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionServiceImpl.java
  backend/src/test/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeServiceUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/lent/repository/LentRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/lent/service/LentServiceImplTest.java
  backend/src/test/java/org/ftclub/cabinet/statistics/service/StatisticsFacadeServiceUnitTest.java
  backend/src/test/java/org/ftclub/cabinet/user/service/LentExtensionServiceTest.java
Labels: FEAT, REFACTOR, BE, FIX

#1487 [FE] FEAT : 테마컬러 서브컬러와 내사물함 변경기능 추가
  frontend/src/components/CabinetInfoArea/AdminCabinetInfoArea.tsx
  frontend/src/components/Card/CardStyles.ts
  frontend/src/components/Card/ThemeColorCard/ColorPicker.tsx
  frontend/src/components/Card/ThemeColorCard/ThemeColorCard.container.tsx
  frontend/src/components/Card/ThemeColorCard/ThemeColorCard.tsx
  frontend/src/components/Card/ThemeColorCard/colorInfo.ts
  frontend/src/components/Club/AdminClubLog.tsx
  frontend/src/components/Club/ClubLogTable.tsx
  frontend/src/components/Common/LoadingAnimation.tsx
  frontend/src/components/LentLog/AdminLentLog.tsx
  frontend/src/components/LentLog/LentLog.tsx
  frontend/src/components/Login/AdminLoginTemplate.tsx
  frontend/src/components/Login/LoginTemplate.tsx
  frontend/src/components/Modals/PasswordCheckModal/PasswordContainer.tsx
  frontend/src/components/SectionPagination/SectionPagination.tsx
  frontend/src/components/UserInfoArea/UserInfoArea.tsx
  frontend/src/index.css
  frontend/src/pages/Layout.tsx
  frontend/src/pages/LogPage.tsx
  frontend/src/pages/PendingPage/PendingPage.tsx
  frontend/src/pages/admin/AdminClubPage.tsx
  frontend/src/pages/admin/AdminLayout.tsx
  frontend/src/types/enum/color.type.enum.ts
  maintenance/index.html
Labels: FEAT, FE

#1492 [BE] DOCS:add_my_name(surlee)#1491
  README.md
Labels: DOCS, BE
