Repository innovationacademy-kr/Cabi, pull requests merged in 2024-04, with the labels that each got.

#1571 [FE] FIX: CLUB 마무리 후작업 #1555
  frontend/src/components/CabinetList/CabinetListItem/CabinetListItem.tsx
  frontend/src/components/Club/ClubInfo.tsx
  frontend/src/components/Club/ClubMemberList/ClubMemberList.container.tsx
  frontend/src/components/Club/ClubMemberList/ClubMemberList.tsx
  frontend/src/components/LeftNav/LeftSectionNav/LeftSectionNavClubs.tsx
  frontend/src/pages/ClubPage.tsx
Labels: FE, FIX

#1570 [FE] FIX: 동아리 페이지 버그 및 사용성 수정 #1562
  frontend/src/components/Card/ClubNoticeCard/ClubNoticeCard.tsx
  frontend/src/components/Club/ClubInfo.tsx
  frontend/src/components/Modals/ClubModal/ClubMemoModal.tsx
Labels: FE, FIX

#1577 [FE] FIX: 내 사물함 버튼 클릭 시 버튼이 깜빡이는 문제 수정 #1576
  frontend/src/components/TopNav/TopNav.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButton/TopNavButton.tsx
  frontend/src/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
Labels: BUG, FE

#1584 [BE] BUG: AllRequestLogInterceptor NPE 수정 #1583
  backend/src/main/java/org/ftclub/cabinet/log/AllRequestLogInterceptor.java
Labels: BUG, BE

#1588 [COMMON] FIX: 수요지식회 Post 패치 #1587
  frontend/src/Presentation/components/Details/DetailContent.container.tsx
  frontend/src/Presentation/constants/policy.ts
  frontend/src/Presentation/pages/Layout.tsx
  frontend/src/Presentation/pages/admin/AdminLayout.tsx
  frontend/src/Presentation/utils/dateUtils.ts
  frontend/src/index.css
Labels: BUG, FE, FIX, COMMON

#1589 [COMMON] FIX: asset 디렉토리 변경에 따른 frontend main cicd 수정 #1586
  .github/workflows/front-cicd.yaml
Labels: FIX, COMMON

#1595 [BE] FIX: 글로벌 에러 핸들링 개선 & 필요한 오류 알림만 상세화하여 보내도록 수정 #1593
  backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordWebAlarmMessage.java
  backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordWebHookMessenger.java
  backend/src/main/java/org/ftclub/cabinet/auth/filter/CachingRequestBodyFilter.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/AdminOauthService.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionController.java
  backend/src/main/resources/log4j2-prod.xml
Labels: BE, FIX

#1599 [BE] HOTFIX: 연체 스케줄러 NPE 수정 #1597
  backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordScheduleAlarmMessage.java
  backend/src/main/java/org/ftclub/cabinet/alarm/discord/DiscordWebHookMessenger.java
  backend/src/main/java/org/ftclub/cabinet/dto/ActiveLentHistoryDto.java
  backend/src/main/java/org/ftclub/cabinet/lent/domain/LentHistory.java
  backend/src/main/java/org/ftclub/cabinet/mapper/LentMapper.java
  backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
Labels: BE, HOTFIX

#1601 DEV TO MAIN
  backend/src/main/java/org/ftclub/cabinet/cabinet/repository/CabinetRepository.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetQueryService.java
  backend/src/main/java/org/ftclub/cabinet/utils/release/ReleaseManager.java
Labels: BE, FIX

#1603 [BE] FIX: 커스텀 에러 (확인된 예외)는 알림을 발송하지 않도록 수정 #1602
  backend/src/main/java/org/ftclub/cabinet/exception/ControllerException.java
  backend/src/main/java/org/ftclub/cabinet/exception/CustomServiceException.java
  backend/src/main/java/org/ftclub/cabinet/exception/DomainException.java
  backend/src/main/java/org/ftclub/cabinet/exception/FtClubCabinetException.java
  backend/src/main/java/org/ftclub/cabinet/exception/ServiceException.java
  backend/src/main/java/org/ftclub/cabinet/exception/UtilException.java
  backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
Labels: BE, HOTFIX

#1606 [FE] UI 리팩토링 #1605
  frontend/package-lock.json
  frontend/src/Cabinet/assets/images/clubIconGray.svg
  frontend/src/Cabinet/assets/images/profile-circle.svg
  frontend/src/Cabinet/assets/images/select.svg
  frontend/src/Cabinet/components/Available/FloorContainer.tsx
  frontend/src/Cabinet/components/Card/Card.tsx
  frontend/src/Cabinet/components/Home/ManualContentBox.tsx
  frontend/src/Cabinet/components/LeftNav/LeftMainNav/LeftMainNav.tsx
  frontend/src/Cabinet/components/LeftNav/LeftSectionNav/LeftSectionNav.tsx
  frontend/src/Cabinet/components/LeftNav/LeftSectionNav/LeftSectionNavClubs.tsx
  frontend/src/Cabinet/components/LentLog/LogTable/LogTable.tsx
  frontend/src/Cabinet/components/MapInfo/MapFloorSelect/MapFloorSelect.tsx
  frontend/src/Cabinet/components/TopNav/TopNavDomainGroup/TopNavDomainGroup.tsx
  frontend/src/Cabinet/pages/LogPage.tsx
  frontend/src/index.css
Labels: BUG, FE, FIX

#1611 Be/dev/feat coin/fix pagination#1604
  backend/src/main/java/org/ftclub/cabinet/dto/CoinHistoryDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/CoinHistoryPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemHistoryDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemHistoryPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemStoreDto.java
  backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
  backend/src/main/java/org/ftclub/cabinet/mapper/ItemMapper.java
Labels: BE, FIX
