Repository innovationacademy-kr/Cabi, pull requests merged in 2024-05, with the labels that each got.

#1615 Common/dev/feat coin/sohyupar#1604
  backend/database/cabi_local.sql
  backend/src/main/java/org/ftclub/cabinet/admin/item/service/AdminItemFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/alarm/config/AlarmProperties.java
  backend/src/main/java/org/ftclub/cabinet/alarm/domain/AlarmEvent.java
  backend/src/main/java/org/ftclub/cabinet/alarm/domain/AvailableSectionAlarm.java
  backend/src/main/java/org/ftclub/cabinet/alarm/handler/AlarmEventListener.java
  backend/src/main/java/org/ftclub/cabinet/alarm/handler/EmailAlarmSender.java
  backend/src/main/java/org/ftclub/cabinet/alarm/handler/PushAlarmSender.java
  backend/src/main/java/org/ftclub/cabinet/alarm/handler/SectionAlarmManager.java
  backend/src/main/java/org/ftclub/cabinet/alarm/handler/SlackAlarmSender.java
  backend/src/main/java/org/ftclub/cabinet/cabinet/domain/Location.java
  backend/src/main/java/org/ftclub/cabinet/dto/CoinHistoryDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/CoinMonthlyCollectionDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemUseRequestDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/MyProfileResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/AlarmItem.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/AlarmStatus.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/ExtensionItem.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/ItemHistory.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/ItemUsage.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/ItemUsageHandler.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/PenaltyItem.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/SectionAlarm.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/SectionAlarmType.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/Sku.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/SwapItem.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/ItemRedis.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/ItemRepository.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/SectionAlarmRepository.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemCommandService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemPolicyService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemQueryService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemRedisService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/SectionAlarmCommandService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/SectionAlarmQueryService.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRedis.java
  backend/src/main/java/org/ftclub/cabinet/lent/repository/LentRepository.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentRedisService.java
  backend/src/main/java/org/ftclub/cabinet/mapper/ItemMapper.java
  backend/src/main/java/org/ftclub/cabinet/mapper/UserMapper.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/BanHistory.java
  backend/src/main/java/org/ftclub/cabinet/user/service/BanHistoryCommandService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/BanHistoryQueryService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionCommandService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/utils/release/ReleaseManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
  backend/src/main/resources/templates/mail/sectionAlarm.html
Labels: FEAT, BE, FIX

#1618 [BE] FIX : Argument Resolver를 통한 UserSessionDto 파라미터 바인딩 구현
  backend/src/main/java/org/ftclub/cabinet/admin/club/service/AdminClubFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/club/domain/ClubRegistration.java
  backend/src/main/java/org/ftclub/cabinet/club/domain/UserRole.java
  backend/src/main/java/org/ftclub/cabinet/club/repository/ClubRegistrationRepoitory.java
  backend/src/main/java/org/ftclub/cabinet/club/service/ClubFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/club/service/ClubPolicyService.java
  backend/src/main/java/org/ftclub/cabinet/club/service/ClubRegistrationCommandService.java
  backend/src/main/java/org/ftclub/cabinet/club/service/ClubRegistrationQueryService.java
  backend/src/main/java/org/ftclub/cabinet/config/ArgumentResolverConfig.java
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/UserAspect.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/UserSessionArgumentResolver.java
  backend/src/test/java/org/ftclub/cabinet/user/repository/UserOptionalFetcherTest.java
Labels: BE, FIX

#1620 Common/dev/feat coin/validate item use request#1604
  backend/src/main/java/org/ftclub/cabinet/dto/ItemUseRequestDto.java
  backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/ItemUseValidator.java
  backend/src/main/java/org/ftclub/cabinet/item/domain/ValidItemUse.java
Labels: FEAT, BE
