Repository innovationacademy-kr/Cabi, pull requests merged in 2024-06, with the labels that each got.

#1623 Common/dev/feat coin/admin/hyowchoi#1604
  backend/src/main/java/org/ftclub/cabinet/admin/statistics/controller/AdminStatisticsControllerV5.java
  backend/src/main/java/org/ftclub/cabinet/admin/statistics/service/AdminStatisticsFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/dto/CoinCollectStatisticsDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/CoinCollectedCountDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/TotalCoinAmountDto.java
  backend/src/main/java/org/ftclub/cabinet/item/controller/ItemController.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/ItemRedis.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemRedisService.java
Labels: FEAT, BE

#1625 Common/dev/feat coin/admin/sohyupar#1604
  backend/src/main/java/org/ftclub/cabinet/admin/dto/AdminItemHistoryDto.java
  backend/src/main/java/org/ftclub/cabinet/admin/dto/AdminItemHistoryPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/admin/item/controller/AdminItemController.java
  backend/src/main/java/org/ftclub/cabinet/admin/item/service/AdminItemFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/admin/statistics/controller/AdminStatisticsControllerV5.java
  backend/src/main/java/org/ftclub/cabinet/admin/statistics/service/AdminStatisticsFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/dto/CoinAmountDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/CoinStaticsDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemAssignPaginationDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemAssignRequestDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemAssignResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemPurchaseCountDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/ItemStatisticsDto.java
  backend/src/main/java/org/ftclub/cabinet/item/repository/ItemHistoryRepository.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemCommandService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemHistoryQueryService.java
  backend/src/main/java/org/ftclub/cabinet/mapper/ItemMapper.java
Labels: FEAT, BE, FIX

#1627 [FE] FIX: Dropdown 컴포넌트 예외처리 추가 #1626
  frontend/src/Cabinet/components/Common/Dropdown.tsx
  frontend/src/Presentation/components/Modals/EditStatusModal/EditStatusModal.tsx
Labels: FE, HOTFIX

#1636 [FE] FIX: intra id로 검색하고 사물함 정보 눌렀을때 잘못된 cabinetInfoArea 뜨는것 해결#1604
  frontend/src/Cabinet/pages/admin/AdminLayout.tsx
Labels: BUG, FE, FIX, v5, HOTFIX

#1645 [FE] REFACTOR 재화 프론트 리팩토링 #1629
  frontend/src/App.tsx
  frontend/src/Cabinet/api/axios/axios.instance.ts
  frontend/src/Cabinet/components/AdminInfo/Chart/CoinUseLineChart.tsx
  frontend/src/Cabinet/components/AdminInfo/Chart/ItemBarChart.tsx
  frontend/src/Cabinet/components/AdminInfo/Chart/PieChartCoin.tsx
  frontend/src/Cabinet/components/AdminInfo/Chart/StoreHorizontalBarChart.tsx
  frontend/src/Cabinet/components/CabinetInfoArea/CountTime/CountTime.container.tsx
  frontend/src/Cabinet/components/Card/Card.tsx
  frontend/src/Cabinet/components/Card/ExtensionCard/ExtensionCard.tsx
  frontend/src/Cabinet/components/Card/LentInfoCard/LentInfoCard.tsx
  frontend/src/Cabinet/components/ItemLog/ItemLogTable/AdminItemLogTable.tsx
  frontend/src/Cabinet/components/ItemLog/ItemLogTable/AdminItemProvideTable.tsx
  frontend/src/Cabinet/components/LeftNav/LeftProfileNav/LeftProfileNav.tsx
  frontend/src/Cabinet/components/LeftNav/LeftStoreNav/LeftStoreNav.tsx
  frontend/src/Cabinet/components/LentLog/LogTable/AdminCabinetLogTable.tsx
  frontend/src/Cabinet/components/LentLog/LogTable/LogTable.tsx
  frontend/src/Cabinet/components/Modals/ClubModal/MandateClubMemberModal.tsx
  frontend/src/Cabinet/components/Modals/ExtendModal/ExtendModal.tsx
  frontend/src/Cabinet/components/Modals/InvitationCodeModal/InvitationCodeModal.container.tsx
  frontend/src/Cabinet/components/Modals/OverduePenaltyModal/OverduePenaltyModal.tsx
  frontend/src/Cabinet/components/Modals/PenaltyModal/PenaltyModal.tsx
  frontend/src/Cabinet/components/Modals/StatusModal/StatusModal.tsx
  frontend/src/Cabinet/components/Modals/SwapModal/SwapModal.tsx
  frontend/src/Cabinet/components/Search/SearchCabinetDetails.tsx
  frontend/src/Cabinet/components/Search/SearchItemByIntraId.tsx
  frontend/src/Cabinet/components/Search/SearchNoCabinetDetails.tsx
  frontend/src/Cabinet/components/Store/Admin/UserStoreInfoArea/UserStoreInfoArea.tsx
  frontend/src/Cabinet/components/Store/CoinLog/CoinLog.tsx
  frontend/src/Cabinet/components/Store/Inventory/InventoryItem.tsx
  frontend/src/Cabinet/components/Store/ItemUsageLog/ItemLogBlock.tsx
  frontend/src/Cabinet/components/Store/StoreCoinPick.tsx
  frontend/src/Cabinet/components/Store/StoreInfo.tsx
  frontend/src/Cabinet/components/TopNav/TopNavButtonGroup/TopNavButtonGroup.tsx
  frontend/src/Cabinet/hooks/useMultiSelect.ts
  frontend/src/Cabinet/pages/ItemUsageLogPage.tsx
  frontend/src/Cabinet/pages/Layout.tsx
  frontend/src/Cabinet/pages/StoreMainPage.tsx
  frontend/src/Cabinet/pages/admin/AdminHomePage.tsx
  frontend/src/Cabinet/pages/admin/AdminLayout.tsx
  frontend/src/Cabinet/pages/admin/AdminStorePage.tsx
  frontend/src/Cabinet/recoil/atoms.ts
  frontend/src/Cabinet/utils/dateUtils.ts
  frontend/src/Presentation/components/Details/DetailContent.container.tsx
  frontend/src/Presentation/components/PresentationLog/LogTable.tsx
  frontend/src/Presentation/utils/dateUtils.ts
Labels: BUG, FEAT, REFACTOR, FE, FIX, v5

#1648 [BE] REFACTOR: 유저 현재 보유 재화를 REDIS -> RDBMS 이전 #1647
  backend/src/main/java/org/ftclub/cabinet/admin/item/service/AdminItemFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/admin/lent/service/AdminLentFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/item/service/ItemRedisService.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
  backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionManager.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserCommandService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
Labels: BE
