Repository innovationacademy-kr/Cabi, pull requests merged in 2024-01, with the labels that each got.

#1506 [COMMON] DOCS: readme 프로젝트 멤버 추가 #1502
  README.md
Labels: DOCS

#1508 [COMMON] KETWORD: DOCS #1503
  README.md
Labels: DOCS

#1509 [COMMON] DOCS: README에 이름 추가
  README.md
Labels: DOCS

#1510 [BE] FEAT: redis backup 기능 추가
  backend/docker-compose.yaml
  deploy-dev/pinpoint-application/docker-compose.yml
  deploy-main/pinpoint-application/docker-compose.yml
  redis/redis.conf
Labels: FEAT, BE

#1513 [FE] FIX: MultiToggleSwitch 이 페이지 전체 button 에 영향을 주지 못하도록 수정#1512
  frontend/src/components/Common/MultiToggleSwitch.tsx
  frontend/src/components/Modals/PasswordCheckModal/PasswordContainer.tsx
  frontend/src/pages/PendingPage/PendingPage.tsx
Labels: FE, FIX

#1516 [COMMON] FEAT: FCM 웹 푸쉬 알림 기능
  .idea/misc.xml
  .idea/modules.xml
  backend/src/main/java/org/ftclub/cabinet/alarm/fcm/FCMInitializer.java
  backend/src/main/java/org/ftclub/cabinet/alarm/fcm/FCMTestController.java
  backend/src/main/java/org/ftclub/cabinet/alarm/fcm/config/FirebaseConfig.java
  backend/src/main/java/org/ftclub/cabinet/alarm/fcm/repository/FCMTokenRedis.java
  backend/src/main/java/org/ftclub/cabinet/alarm/fcm/service/FCMTokenRedisService.java
  backend/src/main/java/org/ftclub/cabinet/alarm/handler/PushAlarmSender.java
  backend/src/main/java/org/ftclub/cabinet/dto/MyProfileResponseDto.java
  backend/src/main/java/org/ftclub/cabinet/dto/UpdateDeviceTokenRequestDto.java
  backend/src/main/java/org/ftclub/cabinet/mapper/UserMapper.java
  backend/src/main/java/org/ftclub/cabinet/redis/service/RedisService.java
  backend/src/main/java/org/ftclub/cabinet/user/controller/UserController.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  frontend/src/api/axios/axios.custom.ts
  frontend/src/components/Card/NotificationCard/NotificationCard.container.tsx
  frontend/src/firebase/firebase-messaging-sw.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/recoil/atoms.ts
  frontend/src/types/dto/user.dto.ts
Labels: FEAT, COMMON

#1537 [BE] HOTFIX: 이전에 블랙홀이었던 유저 대여 시도시, 블랙홀 새로고침 로직 추가 + 연장권 사용 에러 수정
  .idea/misc.xml
  backend/src/main/java/org/ftclub/cabinet/cabinet/service/CabinetQueryService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentCommandService.java
  backend/src/main/java/org/ftclub/cabinet/lent/service/LentFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/domain/User.java
  backend/src/main/java/org/ftclub/cabinet/user/service/BanHistoryCommandService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionCommandService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/LentExtensionQueryService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserCommandService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserFacadeService.java
  backend/src/main/java/org/ftclub/cabinet/user/service/UserQueryService.java
  backend/src/main/java/org/ftclub/cabinet/utils/blackhole/manager/BlackholeManager.java
Labels: BUG, BE

#1527 [COMMON] FEAT: 로그인 후 처리 동작 관련 개선사항
  backend/src/main/java/org/ftclub/cabinet/auth/controller/AuthController.java
  backend/src/main/java/org/ftclub/cabinet/auth/service/AuthFacadeService.java
  frontend/src/App.tsx
  frontend/src/assets/images/sadCcabi.svg
  frontend/src/components/Announce/AnnounceTemplate.tsx
  frontend/src/pages/LoginFailurePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/NotFoundPage.tsx
  frontend/src/pages/PostLogin.tsx
  frontend/src/pages/admin/AdminLoginFailurePage.tsx
  frontend/src/types/enum/AnnounceType.enum.ts
  frontend/stats.json
  maintenance/index.html
Labels: FEAT, COMMON

#1534 [BE] FEAT: 반납일 7,3,1 일전 미리 알람주도록 기능 추가#1518
  backend/src/main/java/org/ftclub/cabinet/alarm/config/AlarmProperties.java
  backend/src/main/java/org/ftclub/cabinet/event/RedisExpirationEventListener.java
  backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueManager.java
  backend/src/main/java/org/ftclub/cabinet/utils/overdue/manager/OverdueType.java
  backend/src/main/java/org/ftclub/cabinet/utils/scheduler/SystemScheduler.java
Labels: BE, FIX
