Repository innovationacademy-kr/Cabi, pull requests merged in 2024-10, with the labels that each got.

#1689 [FE] BUG: 모달에서 링크로 이동 시 모든 창을 닫도록 closeAll 추가 #1668
  frontend/src/Cabinet/components/Modals/Modal.tsx
Labels: BUG, FE

#1693 [FE] FIX: 새로고침 버튼 누를 때 나타나는 스크롤바 제거
  frontend/src/Cabinet/pages/MainPage.tsx
  frontend/src/Cabinet/pages/admin/AdminMainPage.tsx
Labels: FE, FIX, v5

#1692 [FE] BUG: navigate 경로 수정 #1688
  frontend/src/Presentation/components/LeftNav/LeftMainNav/LeftMainNav.container.tsx
Labels: BUG
