Repository innovationacademy-kr/Cabi, pull requests merged in 2025-07, with the labels that each got.

#1808 [BE] FIX: 삭제된 댓글 조회 버그 수정 및 테스트 DB 환경 개선 #1806
  backend/build.gradle
  backend/src/main/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationCommentService.java
  backend/src/main/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotService.java
  backend/src/main/java/org/ftclub/cabinet/presentation/repository/PresentationCommentRepository.java
  backend/src/main/java/org/ftclub/cabinet/presentation/service/PresentationCommentService.java
  backend/src/test/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/admin/presentation/controller/AdminPresentationSlotControllerTest.java
  backend/src/test/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationCommentServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/admin/presentation/service/AdminPresentationSlotServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/presentation/repository/PresentationCommentRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/presentation/repository/PresentationSlotRepositoryTest.java
  backend/src/test/java/org/ftclub/cabinet/presentation/service/PresentationCommentServiceTest.java
  backend/src/test/java/org/ftclub/cabinet/presentation/service/PresentationSlotServiceTest.java
  backend/src/test/resources/application.yml
Labels: BUG, BE, FIX

#1823 [FE] FEAT: 메인페이지 api 연동 및 페이지네이션, 좋아요 기능 추가
  frontend/package-lock.json
  frontend/src/Presentation/api/axios.custom.ts
  frontend/src/Presentation/api/axios/axios.custom.ts
  frontend/src/Presentation/assets/data/maps.ts
  frontend/src/Presentation/components/PresentationCard.tsx
  frontend/src/Presentation/pages/HomePage.tsx
  frontend/src/Presentation/pages/PresentationCardContainer.tsx
  frontend/src/Presentation/types/enum/presentation.type.enum.ts
  frontend/src/components/ui/pagination.tsx
Labels: FEAT, FE, v6

#1828 [BE] FEAT: Presentation 관련 API에 익명 유저 권한 에러 발생 시 401 Http Status Code 반환 기능 추가 #1827
  backend/src/main/java/org/ftclub/cabinet/exception/ExceptionStatus.java
  backend/src/main/java/org/ftclub/cabinet/security/SecurityConfig.java
  backend/src/main/java/org/ftclub/cabinet/security/handler/CustomUnauthorizedAuthenticationEntryPoint.java
  backend/src/test/java/org/ftclub/cabinet/presentation/PresentationIntegrationTest.java
Labels: FEAT, BE

#1833 Fe/presentation renewal/feat layout/#1767
  frontend/src/Cabinet/components/Common/DarkModeToggleSwitch.tsx
  frontend/src/Cabinet/components/TopNav/TopNavDomainGroup/TopNavDomainGroup.tsx
  frontend/src/Presentation/assets/data/maps.ts
  frontend/src/Presentation/assets/images/aboutUs.svg
  frontend/src/Presentation/assets/images/introduce.svg
  frontend/src/Presentation/assets/images/myPageBanner.svg
  frontend/src/Presentation/assets/images/registerBanner.svg
  frontend/src/Presentation/components/CommentSection.tsx
  frontend/src/Presentation/components/LogTable.tsx
  frontend/src/Presentation/components/PresentationCard.tsx
  frontend/src/Presentation/components/PresentationUpdateModal.tsx
  frontend/src/Presentation/components/RegisterForm.tsx
  frontend/src/Presentation/components/TopNav.tsx
  frontend/src/Presentation/pages/AboutUsPage.tsx
  frontend/src/Presentation/pages/HomePage.tsx
  frontend/src/Presentation/pages/Layout.tsx
  frontend/src/Presentation/pages/PresentationCardContainer.tsx
  frontend/src/Presentation/pages/PresentationDetailPage.tsx
  frontend/src/Presentation/pages/ProfilePage.tsx
  frontend/src/Presentation/pages/RegisterPage.tsx
  frontend/src/Presentation/pages/admin/AdminPresentationDetailPage.tsx
  frontend/src/components/ui/footer.tsx
  frontend/src/index.css
Labels: BUG, FEAT, FE, FIX, v6

#1835 [FE] FEAT: no-var eslint 규칙 추가
  frontend/.eslintrc.json
Labels: FE
